### ISSUE TITLE
How to select resolution (quality)

### ISSUE THREAD

**Issue by Sunderlevi** [justfoolingaround/animdl#102]
I can't select the desired resolution (Quality)
Please help me bro....
How to select the downloading resolution (quality) can you give a code for an example
I used animepahe.com website
Even without choosing the quality it goes to default

**Comment by justfoolingaround** [comment]
`animdl stream "animepahe:one piece" -q "480"`

Should work just about fine then.

**Comment by Sunderlevi** [comment]
Quality checks have failed miserably. Returning everything back.
It shows like this
Bro this is best downloader you have made I like it so much but there's only problem I can't select the resolution...👍

**Comment by justfoolingaround** [comment]
Weird that it actually works for me, what anime are you trying to stream?

**Comment by Sunderlevi** [comment]
Actually I am trying to download Attack on Titan 
I pasted the command you have given to me it started downloading but with default resolution
Am I doing something wrong...if possible can you send me a screenshot or a video.
It might be a great help.

**Comment by justfoolingaround** [comment]
Due to some reason quality strings are acting weird. In any case, you can use `-q "[quality='720']"` which forcefully isolates the quality. 

![image](https://user-images.githubusercontent.com/79979949/150686190-9fa1d8fe-9540-48b8-a45d-a4326e9e8764.png)

**Comment by Sunderlevi** [comment]
Thanks bro now it's working...
And thanks for helping me out..
And keep up the good up waiting for your future projects..👍👍
