### ISSUE TITLE
[Inquiry] Download speeds and external download support.

### ISSUE THREAD

**Issue by Sunderlevi** [justfoolingaround/animdl#103]
1. Can we increase the download speed or not
2. A friend of mine used this command on termux on his Android phone it works perfectly for him and he asked if there's another way to download the anime eternally after grabbing the downloading link for eg:Idm lite,UC Browser,chrome and etc (Android)

**Comment by justfoolingaround** [comment]
1. Nope. Download speeds are totally dependent upon two factors:
	- Your ISP bandwidth,
	- The server capacity.

	It is **very** safe to say that animdl has the most straightforward downloader possible and does not decrease your speeds.
2. No such integrations are available for Android, sorry.

**Comment by justfoolingaround** [comment]
`--idm` at the end of the download command.

**Comment by justfoolingaround** [comment]
_Also please make an issue with a suitable issue title._

**Comment by Sunderlevi** [comment]
And when I download anime from Animepahe it downloads in the format of .ts I want to download it in .mp4 file format or it is like this bro..

**Comment by ArjixWasTaken** [comment]
> or it is like this bro..

That makes no sense, what is like what?
As for the download format, animdl is a downloader, not a file converter.
In most cases you can simply rename the file from `.ts` to `.mp4`.
