### ISSUE TITLE
Problem...

### ISSUE THREAD

**Issue by Gojouisthebest** [justfoolingaround/animdl#112]
Sir ,
Actually my speed around here is very high
But when i download from the anime page server it starts downloading in a very low speed.
Is there there any way for increase the downloading speed in anime page server
Like using Thread mode or Debug mode...
And How to use ffmpeg with (example might be a great help)
Please help....😢

**Comment by justfoolingaround** [comment]
_There isn't._ What animdl utilises is already the most optimised internal downloader.

**Comment by Gojouisthebest** [comment]
Can't you like update the program...
Anyways how to use the ffmpeg...
