### ISSUE TITLE
Using ffmpeg

### ISSUE THREAD

**Issue by Gojouisthebest** [justfoolingaround/animdl#113]
how to use the ffmpeg...
With example might be a great help

**Comment by justfoolingaround** [comment]
Read the readme over at [Using ffmpeg](https://github.com/justfoolingaround/animdl#using-ffmpeg).

**Comment by Gojouisthebest** [comment]
Sorry for the late response....
What's a config file how to use it actually i am a beginner
So how to use ffmpeg 
Can you provide me a screenshot.... Please...
And don't close the issue 
If it's get solved i will myself close the issue
