### ISSUE TITLE
FFMPEG Usage

### ISSUE THREAD

**Issue by Gojouisthebest** [justfoolingaround/animdl#114]
Sorry for the late response....
What's a config file how to use it actually i am a beginner
So how to use ffmpeg 
Can you provide me a screenshot.... Please...
And don't close the issue 
If it's get solved i will myself close the issue

_Originally posted by @Gojouisthebest in https://github.com/justfoolingaround/animdl/issues/113#issuecomment-1049957485_

**Comment by justfoolingaround** [comment]
Just make an `animdl_config.yml` file on your working directory and copy the required ffmpeg configurations.
