### ISSUE TITLE
AnimeFLV

### ISSUE THREAD

**Issue by KasukeLp23** [justfoolingaround/animdl#119]
Would it be possible to add the site?

Name: AnimeFLV 
URL: https://www3.animeflv.net/
Language: Spanish

**Comment by KasukeLp23** [comment]
Thank you

**Comment by justfoolingaround** [comment]
Update on this, this will be added if (god forbid) for some reason about 50% of the current providers are broken beyond repair.

**Comment by justfoolingaround** [comment]
Closed for #151
