### ISSUE TITLE
Animepahe and ts

### ISSUE THREAD

**Issue by sbo2401** [justfoolingaround/animdl#120]
Good day, I tried downloading from animepahe and it didn't work and I noticed that when downloading from gogoanime, it downloads in ts format by default and not mp4 after updating and when I tried using an older version of animdl, it didn't even work.

**Comment by brahmkshatriya** [comment]
Please refer [this comment](https://github.com/justfoolingaround/animdl/issues/103#issuecomment-1020215149)

**Comment by sbo2401** [comment]
> Please refer [this comment](https://github.com/justfoolingaround/animdl/issues/103#issuecomment-1020215149)

**Comment by sbo2401** [comment]
> Please refer [this comment](https://github.com/justfoolingaround/animdl/issues/103#issuecomment-1020215149)

This issue doesn't address animepahe not working and ts file encoding is different from mp4 so renaming file extension doesn't work

**Comment by brahmkshatriya** [comment]
animdl is just a downloader & provider, it does not convert mp4 to ts.
You can use ffmpeg to convert ts files to mp4, or just directly play the ts file (renaming doesn't make any changes to the file itself & the video players generally do not look at the file extension, and rather directly see what the video was encoded in, So in this case .mp4 extension is just a placebo.)

And for animepahe,
Looks like its working just fine https://github.com/justfoolingaround/animdl-provider-benchmarks

Maybe try checking if its working for you on the website itself

**Comment by justfoolingaround** [comment]
> Good day, I tried downloading from animepahe and it didn't work and I noticed that when downloading from gogoanime, it downloads in ts format by default and not mp4 after updating and when I tried using an older version of animdl, it didn't even work.

AnimePahe seems to be working just fine. It downloaded a HLS stream from GogoAnime. It is fully normal that a stream was HLS. 

Of course an older version of animdl would not work. 

![image](https://user-images.githubusercontent.com/79979949/158332697-bed5e4ff-56db-4718-be1d-4adf14015e32.png)
