### ISSUE TITLE
Change default provider

### ISSUE THREAD

**Issue by Otakuzu** [justfoolingaround/animdl#121]
Hello! im a noob so please dont be mad at me for asking :( 

I wish to change the default provider to animepahe , it is possible? with the latest update it defaults to Zoro.
 tried touching a file in /usr/local/lib/python3.8/dist-packages/animdl-1.4.84-py3.8.egg/animdl/core/config but it does nothing . 

thanks for reading!!

**Comment by FlawLessx** [comment]
try using query, example `animdl stream "animepahe:one piece" -r 1`
see the documentation web search prefixer

**Comment by Otakuzu** [comment]
i wanted to get animepahe as default because is easier and less typing 

I managed to fix it by editing the file __init__.py located in 
/home/USERNAME/.local/lib/python3.8/site-packages/animdl/core/config

maybe someone else find this useful :)
