### ISSUE TITLE
StreamSB extractor returns 404

### ISSUE THREAD

**Issue by FlawLessx** [justfoolingaround/animdl#122]
"I have upgraded the project to its latest version, checked the open issues for any duplicates, am not spamming multiple same or similar issues and **have not edited the code myself**. In any of those cases, a maintainer may **CLOSE** or **DELETE** the issue without any notices."

From maintainer: Your title should answer at least 2 or 3 of 5W1H questions for fastest responses.

**Describe the bug**
StreamSB extractor returns 404

**Did the error occur in between an active task (`download` / `stream` / `grab`)?**
I just try running hardcoded the extractor code, not from cli

**Screenshots [Optional]**
![image](https://user-images.githubusercontent.com/60551421/156952747-b3fb727b-56ff-4048-8bd6-07b322a636f8.png)

**Additional information**
 - Link used: https://sbplay2.com/e/7kd3c71i4rex?caption_1=https://sub.asianembed.io&sub_1=English

**Comment by justfoolingaround** [comment]
Could potentially be an algorithm change on their side, will fix.

**Comment by justfoolingaround** [comment]
Fixed, works perfectly with the link provided. Thanks for reporting this issue.
