### ISSUE TITLE
httpx's ConnectError: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by TheOnlyKiyotaka** [justfoolingaround/animdl#123]
I installed the script using Python pip and when I try to use it, it gives me this error:

>                                            justfoolingaround/animdl - v1.4.84                                           
>                                     A highly efficient anime downloader and streamer                                    
> Traceback (most recent call last):
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_exceptions.py", line 8, in map_exceptions
>     yield
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\backends\sync.py", line 57, in start_tls
>     raise exc
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\backends\sync.py", line 52, in start_tls
>     sock = ssl_context.wrap_socket(
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
>     return self.sslsocket_class._create(
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
>     self.do_handshake()
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1123)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
>     yield
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
>     resp = self._pool.handle_request(req)
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\connection_pool.py", line 253, in handle_request
>     raise exc
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
>     response = connection.handle_request(request)
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\http_proxy.py", line 255, in handle_request
>     connect_response = self._connection.handle_request(
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\connection.py", line 86, in handle_request
>     raise exc
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\connection.py", line 63, in handle_request
>     stream = self._connect(request)
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_sync\connection.py", line 150, in _connect
>     stream = stream.start_tls(**kwargs)
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\backends\sync.py", line 57, in start_tls
>     raise exc
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 135, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
>     raise to_exc(exc)
> httpcore.ConnectError: EOF occurred in violation of protocol (_ssl.c:1123)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\Scripts\animdl-script.py", line 33, in <module>
>     sys.exit(load_entry_point('animdl==1.4.84', 'console_scripts', 'animdl')())
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1128, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1053, in main
>     rv = self.invoke(ctx)
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1659, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1395, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 754, in invoke
>     return __callback(*args, **kwargs)
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\animdl\core\cli\helpers\fun.py", line 122, in internal
>     latest, version = check_for_update()
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\animdl\core\cli\helpers\fun.py", line 111, in check_for_update
>     r'__core__ = "(.*?)"', client.get(git_version_url).text
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 1025, in get
>     return self.request(
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 802, in request
>     return self.send(request, auth=auth, follow_redirects=follow_redirects)
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 889, in send
>     response = self._send_handling_auth(
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 917, in _send_handling_auth
>     response = self._send_handling_redirects(
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 954, in _send_handling_redirects
>     response = self._send_single_request(request)
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_client.py", line 990, in _send_single_request
>     response = transport.handle_request(request)
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
>     resp = self._pool.handle_request(req)
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 135, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "C:\Users\amir\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
>     raise mapped_exc(message) from exc
> httpx.ConnectError: EOF occurred in violation of protocol (_ssl.c:1123)

The command used:

> animdl stream "one piece" -r 1

I tried a few more commands, but they all gave me this same error. I have no problem with running "animdl --help", but when I try to actually watch an episode by using "animdl stream", it gaves me an error. I'll appreciate an answer.

**Comment by justfoolingaround** [comment]
Seems like a firewall or internet issue. Nothing much I can do about it.

**Comment by TheOnlyKiyotaka** [comment]
Is there anything that I can do to fix it?
Or is it unfixable?

**Comment by TheOnlyKiyotaka** [comment]
Okay, nevermind. I fixed it by turning off the v2ray proxy I was using and it's working perfectly.
