### ISSUE TITLE
Idea.....

### ISSUE THREAD

**Issue by Itmedesu** [justfoolingaround/animdl#126]
I have made a script which allows to scrap the download link from Animepahe website...
If you want the script (code) I will be happy to share it with you

**Comment by brahmkshatriya** [comment]
Like direct download links? & Not the links from the video player embed

**Comment by Itmedesu** [comment]
Yeah....

**Comment by justfoolingaround** [comment]
Be clear and if you want to, share the code. Don't make these attention seeking issues.
