### ISSUE TITLE
Zoro community timestamps for automatic intro skipping

### ISSUE THREAD

**Issue by banxhu** [justfoolingaround/animdl#127]
"I will be patient, civil and will not make a comment inquiring the ETA unless the last ETA inquiry occurred more than 4 weeks or 28 days ago. I have checked all the open and closed issues to get to the conclusion that my suggestion is unique and not added previously. In violation of any of these, a maintainer can **DELETE** or **CLOSE** my issue without any notices."

From maintainers: Both labels have been handed to this issue, remove the inapplicable one. Your title should answer at least 3 of 5W1H questions for fastest responses.

**Is your feature request related to a problem? Please describe.**
What it does is try's to parse the zoro.to's messages that are below and detects all the valid timestamps and then searches among them the ones with the "title" option and then among them all if there is a liked one, its given preference, and then somehow add this functionality to the project. To skip to that time. 

I am ready to contribute if I get time.

**Comment by banxhu** [comment]
![Screenshot_2022-03-12-07-58-34_1920x1080](https://user-images.githubusercontent.com/99345227/158021981-974e50e8-3bef-4534-85bd-4dfd2f460681.png)
The messages like this^

**Comment by banxhu** [comment]
Hmm, no comments.

**Comment by justfoolingaround** [comment]
I don't think this would be that reliable enough of a feature to add to the project tbh.
