### ISSUE TITLE
Gogoanime Not Working

### ISSUE THREAD

**Issue by sbo2401** [justfoolingaround/animdl#129]
![Screenshot from 2022-03-29 09-53-41](https://user-images.githubusercontent.com/40143366/160574580-55c16ba9-4c43-4271-84b8-0af71ec91125.png)
This is what happens when i try using gogoanime and it started this morning

**Comment by justfoolingaround** [comment]
Fixed just now at version `.93`. Thanks for reporting this issue.

**Comment by sbo2401** [comment]
Thank you very much

**Comment by sbo2401** [comment]
![Screenshot from 2022-05-18 11-29-48](https://user-images.githubusercontent.com/40143366/169020448-aaeb34ef-2e2f-435a-958d-9ce03642a936.png)
This is the new issue i am getting

**Comment by justfoolingaround** [comment]
Can't reproduce, the downloads seem to be working fine at least for me.
