### ISSUE TITLE
Prefer sub no dub [crunchyroll]

### ISSUE THREAD

**Issue by OilSubjectLoss7** [justfoolingaround/animdl#134]
It keeps dowloading the dub one.

**Comment by justfoolingaround** [comment]
Please specify which content does this.

**Comment by OilSubjectLoss7** [comment]
> Please specify which content does this.

Crunchyroll

**Comment by justfoolingaround** [comment]
Content, as in the anime name.

**Comment by justfoolingaround** [comment]
Oops, my bad.

**Comment by justfoolingaround** [comment]
Closed due to inactivity.
