### ISSUE TITLE
Extraction from 'gogoplay' failed 

### ISSUE THREAD

**Issue by Kingslayer047** [justfoolingaround/animdl#135]
The Error occurs in grab command when grabbing anime from cli  the pretty much works for all other site but recently, the grabber isn't working for gogoanime whenever I use the grab command , it throws the error :

`Extraction from 'gogoplay' failed due to: JSONDecodeError('Expecting value: line 1 column 1 (char 0)').`

**Screenshots [Optional]**
![image](https://user-images.githubusercontent.com/55092235/163579910-a7f0807f-40a2-48b7-a4f2-642f2250fdf2.png)
![image](https://user-images.githubusercontent.com/55092235/163579925-10b46256-73d4-47d5-ae01-9d9916d8a8af.png)
![image](https://user-images.githubusercontent.com/55092235/163579965-f4a3d40c-fe71-49bb-add0-7a3ffba9e7e4.png)

**Additional information**
- animdl version : 1.5.42
- The site and provider this issue is related to : gogoanime

**Comment by justfoolingaround** [comment]
Fixed as of the latest push.

Try updating to `1.5.43`.

**Comment by Kingslayer047** [comment]
Worked for 30 mins or so  after updating to `1.5.44`

Same error pops up , now.

![image](https://user-images.githubusercontent.com/55092235/163589455-8e06ae56-8e9b-423f-83af-6371ab57f48c.png)

**Comment by iamchokerman** [comment]
fixed again in 45
