### ISSUE TITLE
A Standalone executable with automated installation script and enhancement

### ISSUE THREAD

**Issue by Justaus3r** [justfoolingaround/animdl#14]
Hello,
Got an eye on your project and it's great,there is one problem you need to have python installed and lets be real not every one who watches anime, is a programmer or there can be some other problem.i had a little time to spare from my exams, so i created a standalone executable for your script using [Nuitka(a python compiler)](https://github.com/Nuitka/Nuitka).it converts all the constructs to c,c++ so there is a significant boost over cpython.also i created a batch script(animedl_install.bat) for installation that automatically copies all the files to ```C:\Program Data``` and adds the executable to PATH.i could have created a installer but that would have needed some modification to your animedl.py file and i was lazy for that(but if you need i can create one).so after installation you just need to open cmd and type ```animedl``` to get started.i have uploaded the zip over my [mega](https://mega.nz/file/U4lkWAKB#xf84tGL2RD9OYKrlLRGyv6oJbNd0ANuhssh6UgAnc8c) account.one more thing ,i recommend you also having a interactive user interface,for example if user uses it from cmd with arguments then run it like its running now but if user runs the executable or python script without giving any argument(i.e grab,download) then run it in a interactive mode with a menu like in [this repo](https://github.com/Justaus3r/Anfu) or better.its a sorry state script (using curses programming in python) i wrote a while back.supports selecting options from keyboard keys(UP/DOWN) and also mouse support.i can help you with the interactive menu,that is if i get any time from my exams😅.also one more thing ,add versioning to your git repo

i hope that you go with some of my recommendations
regards,

**Comment by justfoolingaround** [comment]
_\*sigh\*_ It is animdl, the removal of "e" is intended for kinda differentiating from the crowd of "anime-dl"(s) xd.

And yep, I agree with making a packaged version, kinda want to set a workflow for that so that would take place automatically with each push. (_I am figuring workflows out and I kinda expect to do such automagical git stuff soon enough_)

I kinda have plans on an interactive UI, its just that, I'm a student and well, assuming you have exams atm, you know how that goes for a developer; a tough schedule. On top of that, being a backend developer doesn't help at all as it makes UI programming (except CUI) a bit more time consuming, not to mention a headache. The only reason `click` was implemented was because it was made by PalletProjects, the same guys who created Flask. 

Versioning.. uh.. yep.. that's kinda being done [here](https://github.com/justfoolingaround/animdl-install) atm, I'm not to proud of it xd. I will look through proper ways and hopefully a better versioning would be done in this repo :).

**Comment by Justaus3r** [comment]
>>*sigh* It is animdl, the removal of "e" is intended for kinda differentiating from the crowd of "anime-dl"(s) xd.

Sorry for that it was an accident ,i am sure i changed and fixed that but i think i forgot on changing it in archive(my bad 😅).
For the packaged versions,you can always upload them along side your releases,i saw that you haven't created a release.github supports that and i think you should draft a release like this one:
![Releases](https://user-images.githubusercontent.com/72691864/123506705-12d3e780-d67f-11eb-9637-73e5d810e981.png)

This can help you with versioning your script and also with packaged versions as you can add packaged versions with every release.also you can add release notes with every release.this is a very good practice used by almost every developer.your release page will look like this(except that you will have archive containing the standalone version):
![rel](https://user-images.githubusercontent.com/72691864/123506887-f2f0f380-d67f-11eb-9151-b59a59b5cda8.png)

Github actually has documentation for [creating a release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository)

For the UI it Depends,if you want to create a MDI(menu driven interface) having options then it's not that hard but also not very interactive and appealing or if you want to create a TUI(textual user interface) like [this](https://camo.githubusercontent.com/cbbfff5605effe0de3b45317af479f2eb122e91c4acd09118fcbfa00196d8a61/68747470733a2f2f64726976652e676f6f676c652e636f6d2f75633f6578706f72743d646f776e6c6f61642669643d314f486865794f464433386a41432d33516a676759737664574e65396474383657) one .it will take some time and understanding of [curses module(a wrapper for c,c++ ncurses library)](https://docs.python.org/3/howto/curses.html)but it is far more interactive,you can use Keyboard keys, mouse and many more things.atlast if you want to create a GUI ,then it depends whether you have learned any gui frameworks like tkinter or pyqt5 and if you haven't and you want to create a GUI then i **highly** encourage you to learn [pysimplegui](https://github.com/PySimpleGUI/PySimpleGUI)

**Comment by Justaus3r** [comment]
I checked the standalone(executable) version and it seems to be working fine,there are some recommendations tho,you are using Unicode characters for coloring your text.it works fine in windows-terminal(cuz it emulates cmd and adds a proper unicode support) **BUT** it does not work in cmd as cmd doesn't have alot of support for unicode characters.i think you should use a cross-platform library like [rich](https://pypi.org/project/rich/).its an excellent library and using it is like childs-play,consider following minimal example:
```
from rich import print # rich has its own print function just like cpython's 


print("[red]Never gonna give you up[/red]")
print("[green]Never gonna let you down[/green]")
print("[purple]Never gonna run around and desert you[/purple]")
print("[cyan]Never gonna make you cry[cyan]")
print("[yellow]Never gonna say goodbye[/yellow]")
print("[gold1]Never gonna tell a lie and hurt you[/gold1]")
```
will *rickroll* you in different colors ,its cross-platform meaning it runs on linux,windows and mac and has alot more than coloring text(given that your shell program supports them).

**Comment by justfoolingaround** [comment]
Oh boy, now that's a lot of work to do. I'll look through all of this and add it to the codebase where required.

Luckily for me, I've made a centralized "to_stdout" function internally. (Also, it should be working on cmd too though 🤔)

Aight, the updates will roll based off of this! Thanks for the wonderful suggestions!

**Comment by Justaus3r** [comment]
>>THANK YOU LOL rich IS INCREDIBLE!
no prob
>>Also, it should be working on cmd too though 
it doesn't because cmd interpreter doesn't have a very good support for unicode and other encodings that's why they created windows terminal.
>>*Just a thought ,i think you should change the name to AniDl*
For the name will you change it?

**Comment by justfoolingaround** [comment]
> it doesn't because cmd interpreter doesn't have a very good support for unicode and other encodings that's why they created windows terminal.

I mean... it is fairly colorful enough, and yeah rich will be used all over the project soon:
![image](https://user-images.githubusercontent.com/79979949/123520092-be585880-d6ce-11eb-8eb4-5e75d3612bc3.png)

> For the name will you change it?

No plans at the moment, thanks for the suggestion though.

> also if its not a problem what is this "to_stdout" function that u refer?

Oh, there's a core function that handles printing to the console I added because I was advised, by a certain individual that many program/modules suffer when there isn't a stdout stream monitoring (a good method for filtering and formatting).

For instance, that function in animdl looks like this: 
```py
def to_stdout(message, caller='animdl'):
    return print("[\x1b[36m%s\x1b[39m] %s" % (caller, message))
```

**Comment by Justaus3r** [comment]
> 
> 
> > it doesn't because cmd interpreter doesn't have a very good support for unicode and other encodings that's why they created windows terminal.
> 
> I mean... it is fairly colorful enough, and yeah rich will be used all over the project soon:
> ![image](https://user-images.githubusercontent.com/79979949/123520092-be585880-d6ce-11eb-8eb4-5e75d3612bc3.png)

is this in opened cmd(i mean is the cmd opened from windows-termianl or independently)?
>>No plans at the moment, thanks for the suggestion though.
 
aight i see



>>Oh, there's a core function that handles printing to the console I added because I was advised, by a certain individual that many program/modules suffer when there isn't a stdout stream monitoring (a good method for filtering and formatting).

i see ,thnx

**Comment by justfoolingaround** [comment]
Yep, it is in a independent instance of cmd.

**Comment by Justaus3r** [comment]
> 
> 
> Yep, it is in a independent instance of cmd.

Oh i see,well if its working perfectly like you intended then there is no need to add up more dependencies,if you want your program to be fancier, well then yeah give rich  a try

**Comment by Justaus3r** [comment]
Hey,(Sorry if am disturbing and for making this issue a discussion box.i was bored,decided to work on a little project of mine,but it frustrates me so i decided to check out your code.  _**you might be thinking why this guy keeps commenting on a issue and am really sorry for that**_ 😅)

There are somethings i want to ask and some suggestions:
- in ```core/config/__init__.py``` ,line 42 (i.e:if CONFIGURATION_FILE_PATH.exists():) ,you are checking if the json file exists,it loads it but if it doesn't exist.wouldn't it breakup the code,(unless you have implemented error handling and i didn't saw it).even if you have ,i say you instead add a try;except block ,cuz conditional statements tend to slow down the programs also try;except blocks increase the scalability of error handling,what if the file exists but the user doesn't have permission,the current code will just crash.following code should be a better workaround for it
```
try:
    with open(CONFIGURATION_FILE_PATH, 'r') as conf:
        CONFIG = merge_dicts(DEFAULT_CONFIG, json.load(conf))
except (FileNotFoundError,PermissionError): #you can also add more exceptions
    #code if the conf is not loaded successfully
```
- i dont understand the merge_dicts() function.you are searching for your object in ``dict```(line:8) dictionary but isn't predefined,how is your item present in a predefined dictionary ?(sorry i am not a ideal python programmer)

- in animdl/core/cli/helpers/mpv.py,you are using subprocess module ,you are manualling creating a list for the command i.e``` args = [MPV_EXECUTABLE, stream_url, '--force-window=immediate']``` ,you can automate this process by using the _**split**_ method of shlex,i.e:
```
import shlex
import subprocess

cmd = f"{MPV_EXECUTABLE} {stream_url} --force-window=immediate" # your command ,edit it however u like
arg = shlex.split(cmd) # will create a list for your string,pretty handy
subprocess.Popen(arg)
```
also instead of using ```subprocess.Popen(arg)``` use ```subprocess.Popen(arg,check=True) and wrap the statement around try;except block,i.e:
```
import shlex
import subprocess

cmd = f"{MPV_EXECUTABLE} {stream_url} --force-window=immediate" # your command ,edit it however u like
arg = shlex.split(cmd) # will create a list for your string,pretty handy
try:
    subprocess.Popen(arg,check=True) # will raise a exception if there's something wrong with the command ,we handle this exception and give a proper message instead of some gibrish 
except Exception:
    print("An Error occured,possibly because mpv is not installed or something's wrong while fetching data")
this will ensure a good exception handling.
```

- Also when do you create the ```ANIMDL_CONFIG``` environmental variable and where is ```animdl_config.json``` present.

**Comment by justfoolingaround** [comment]
It's fine lol, an active issue doesn't really bother me at all, you can drop all your questions and queries.
-
- Nope, the inexistence of the config file won't affect the codebase, there's a `pathlib.Path.exists()` check right above it.

- The dict merging is recursive; in line 8, it's a type check, that is, if the object within a dict is the type `dict` it'll call the function again (recursion).

- Ah, as much as I'd love to use shlex, it's really not required as a value needs to be added in the similar way if any further arguments are required.

- `subproces.Popen` in this codebase won't really help much about errors as there are countless checks that help make all the requirements fulfill. And, there's simply a return code check (in this codebase, it's handy because mpv doesn't have specification on the cause of it.)

- The environment variable is for VPS or a dedicated server so that the location of the config file doesn't need to be with the codebase. The default location for the config file is `./animdl_config.json` which is in the working directory.

If you need to talk about more stuff, a discord would be more convenient: `KR#5753`

**Comment by Justaus3r** [comment]
>> - It's fine lol, an active issue doesn't really bother me at all, you can drop all your questions and queries.
>> - If you need to talk about more stuff, a discord would be more convenient: KR#5753

Oh Thanks ,and yeah will reach u out on discord for queries

>> - Nope, the inexistence of the config file won't affect the codebase, there's a pathlib.Path.exists() check right above it.
>> - The environment variable is for VPS or a dedicated server so that the location of the config file doesn't need to be with the codebase. The default location for the config file is ./animdl_config.json which is in the working directory.

i see the ```CONFIGURATION_FILE_PATH``` is optional if it exists then you are merging ```DEFAULT_CONFIG```  with the json file which in python is also treated same as dictionaries.that was stupid of me ,not seeing it.

>> And, there's simply a return code check

yeah i saw that,if mpv doesn't exist you simply don't have the ```stream``` command,must say a clever thing.thnx again for the help

regards,

**Comment by crazyaccess** [comment]
Yare Yare

**Comment by justfoolingaround** [comment]
Finally! A release was made using `Nuitka`. Must say that it is in fact an amazing tool! Thank you @Justaus3r.

**Comment by Justaus3r** [comment]
@justfoolingaround no problem,yeah it is,its 300% faster than cpython and the maintainer  is actively developing it.also its crossplatform meaning u could make binaries for linux and mac also.i would have create d it for ya but i have my final examination of chemistry course nd i freakin hate it.well after my exams ,am gonna learn kiwy framework so maybe if time serves ,will make a android port for this tool
