### ISSUE TITLE
AniWorld

### ISSUE THREAD

**Issue by HarexeW** [justfoolingaround/animdl#141]
Site: AniWorld
Url: https://aniworld.to/
Lang: German

**Comment by justfoolingaround** [comment]
Sure, will check and consider when the project requires a new provider.

**Comment by justfoolingaround** [comment]
Update on this, this will be added if (god forbid) for some reason about 50% of the current providers are broken beyond repair.

**Comment by justfoolingaround** [comment]
Closed for #151.
