### ISSUE TITLE
Feature Request: Lookup User’s Watching List to queue in a stream session

### ISSUE THREAD

**Issue by aizuchan** [justfoolingaround/animdl#142]
Hi Again!, @justfoolingaround

_A feature request again… I hope you don’t mind…_
I realized something while I am using `animdl` is that: It’s a bit of a pain to type in the anime name every time I want to watch anime. So…

Here’s the idea: I think it would be really cool to make `animdl` look up the user’s watching list (user id stored in a config or something) on the tracking sites (AniList, MyAnimeList, etc…) fetch that list and makes the user choose what they want to watch based on their list and queue up the episodes of anime that user haven’t watch yet for them to watch.

BTW, the integration of `fzf` is really awesome!
Thank you for your time!

**Comment by brahmkshatriya** [comment]
![image](https://user-images.githubusercontent.com/69040506/168431674-da30a7b2-1ed1-4497-83a3-1c1c7960097a.png)
:prayge:

**Comment by aizuchan** [comment]
If this is too much, That's ok. Please ignore and close this. It's just an idea that popped into my head.
Might be a bit too much to ask for really...

**Comment by brahmkshatriya** [comment]
might wanna wait for KR's response

**Comment by justfoolingaround** [comment]
Tracker support, local content watch history is quite a bit difficult, at least currently. I'll get back to this if any plans are made to integrate this, most probably in v2.
