### ISSUE TITLE
Option to set default download folder in config.yml

### ISSUE THREAD

**Issue by expacc007** [justfoolingaround/animdl#147]
^title

**Comment by justfoolingaround** [comment]
Uhh, `cd`. You basically use the project on your terminal's directory.

**Comment by expacc007** [comment]
Sorry, my mistake. Actually I meant an option to set default download folder in config.yml. It can be done through the -d flag, but for example: If you always download to the same folder, then you can set path to the folder in config.yml then it will be downloaded to the specified folder irrespective of your terminal's directory.

**Comment by justfoolingaround** [comment]
Btw will add this when I get the time, just a little bit busy atm.

(I don't suggest opening PRs for this as this could be rather complex for anyone unfamiliar with the code structure.)

**Comment by justfoolingaround** [comment]
Added to config as `download_directory` key as of `1.5.84`.
