### ISSUE TITLE
Add an option to grab the anime title as well

### ISSUE THREAD

**Issue by Farzat07** [justfoolingaround/animdl#149]
"I will be patient, civil and will not make a comment inquiring the ETA unless the last ETA inquiry occurred more than 4 weeks or 28 days ago. I have checked all the open and closed issues to get to the conclusion that my suggestion is unique and not added previously. In violation of any of these, a maintainer can **DELETE** or **CLOSE** my issue without any notices."

From maintainers: Both labels have been handed to this issue, remove the inapplicable one. Your title should answer at least 3 of 5W1H questions for fastest responses.

**Is your feature request related to a problem? Please describe.**
I am writing a script to play episodes as an mpv playlist instead of 1 file at a time. The script takes the url only as input. I want to set the title to "<insert title> E<insert episode number>", but I don't see any easy way to obtain the anime title from the url.

**Describe the solution you'd like**
A way to obtain the title of an anime given its url (possibly as a separate request).

**Describe alternatives you've considered**
Instead of using the URL of the anime, I could use the search command to obtain the title and url, and then use the URL. However when opening from the browser, this adds a manual step which I want to eliminate.

**Additional context**

**Comment by justfoolingaround** [comment]
As of `1.5.84`, the `search` will be able to recognise your URLs and hand you their title.

```sh
$ animdl search "https://9anime.to/one-piece.ov8" --json -ll 0
{"name": "One Piece", "anime_url": "https://9anime.to/watch/one-piece.ov8"}
```

**Comment by Farzat07** [comment]
Thanks
