### ISSUE TITLE
Pypresence crashes the app without discord running

### ISSUE THREAD

**Issue by cronyakatsuki** [justfoolingaround/animdl#154]
After installing python-pypresence on arch for discord rpc support animdl started crashing when not having discord opened even when just running the `animdl` command itself without streaming or downloading anything. I have updated to the newest version of animdl using the aur.

![Imgur](https://i.imgur.com/qQVhFG5.png)

Is there a possibility to ad a check that will make it so that the app doesn't crash without discord running with pypresence installed?

**Comment by justfoolingaround** [comment]
Sorry, forgor to commit 💀. Fixed as of `1.8.90`.
