### ISSUE TITLE
Downloaded files are empty when downloading 2nd season of Komi-san

### ISSUE THREAD

**Issue by j4wshua** [justfoolingaround/animdl#157]
When downloading Komi-san wa, Comyushou desu. 2nd Season / https://animixplay.to/v1/komi-san-wa-comyushou-desu-2nd-season, all files (but episode 7, which throws an error) are empty.

Here is animdl's output on `aninmdl download komi`
https://pastebin.com/WbK6LreT

**Comment by justfoolingaround** [comment]
Was due to the global referer, fixed as of `1.8.90`.
