### ISSUE TITLE
simple Gui for animdl

### ISSUE THREAD

**Issue by eslamsidereel** [justfoolingaround/animdl#163]
**Animdl** is my favorite tool for watching anime. It works perfectly and I haven't encountered any kind of problems so far.
I was wondering if it possible to create a simple **GUI** for **animdl**?
A little window to display the output, a button to submit, a couple of dropdown menus for quality selection and provider selection and finally a checkbox for streaming or downloading.
Currently I have to write every thing in a txt file then copy paste to a CMD terminal. It's a hassle so I hope if it posible to make the GUI?

Edit: Unfortunately, I am a graphic designer so I have no knowledge in coding, just a little html and php.
I tried using a GUI maker like [UGUI.io](https://ugui.io/) and I managed to create the button, the selection menus and the dropdown menus, but unfortunately I could get it to work because the return text wasn't complete and the submit button would restart again thus it's useless.

![Screenshot 2022-07-11 183253](https://user-images.githubusercontent.com/45595948/178313333-e6412472-a3ad-4166-8cbe-501911efa4ab.jpg)

![Screenshot 2022-07-11 183443](https://user-images.githubusercontent.com/45595948/178313722-97a53af3-4e12-4eb9-b68a-3ca1caa6c597.jpg)

"I will be patient, civil and will not make a comment inquiring the ETA unless the last ETA inquiry occurred more than 4 weeks or 28 days ago. I have checked all the open and closed issues to get to the conclusion that my suggestion is unique and not added previously. In violation of any of these, a maintainer can **DELETE** or **CLOSE** my issue without any notices."

**Comment by omaru-ok** [comment]
> Edit: Unfortunately, I am a graphic designer so I have no knowledge in coding, just a little html and php. I tried using a GUI maker like [UGUI.io](https://ugui.io/) and I managed to create the button, the selection menus and the dropdown menus, but unfortunately I could get it to work because the return text wasn't complete and the submit button would restart again thus it's useless.
> 
> ![Screenshot 2022-07-11 183443](https://user-images.githubusercontent.com/45595948/178313722-97a53af3-4e12-4eb9-b68a-3ca1caa6c597.jpg)
> 
> "I will be patient, civil and will not make a comment inquiring the ETA unless the last ETA inquiry occurred more than 4 weeks or 28 days ago. I have checked all the open and closed issues to get to the conclusion that my suggestion is unique and not added previously. In violation of any of these, a maintainer can **DELETE** or **CLOSE** my issue without any notices."

ayo i recoomadn ya'll to make TUI . like [mangal](https://github.com/metafates/mangal)

**Comment by justfoolingaround** [comment]
I don't think a TUI will make it to animdl anytime soon. I'll re-opon when plans are made but for now, yeah no.
