### ISSUE TITLE
How to set-up fzf and stream command is unavailable 

### ISSUE THREAD

**Issue by toonpedia** [justfoolingaround/animdl#164]
Hello I am new to using this type of repositories and stuff so sry in advance for my request. First of all thanks for making this awesome repository. I am really glad i found it. But I am unable to stream anime with cmd: animdl stream attack On titan. it shows error and asks to use animdl --help to know supporting commands. 2)I want to use fzf ui but i am unable to do so or more like i dont know how to do so.

**Comment by athulrajts** [comment]
if the name of the anime has spaces, you need to surround it with double quotes
animdl stream "attack on titan"

**Comment by NaiveInvestigator** [comment]
For the fzf part actuallt add these lines to the config file

```
fzf:
    executable: fzf
    opts: []
    state: true
```

YEP the state should be `true` lol not `false` like it is shown in the README. That is what worked for me.

**Comment by justfoolingaround** [comment]
Oof, the readme has been fixed. For the `stream` command, please make your any of the supported streamers are in PATH.
