### ISSUE TITLE
Banner is not disable when index and log level are used

### ISSUE THREAD

**Issue by toomyzoom** [justfoolingaround/animdl#168]
**Describe the bug**

Banner still shows despise setting index and log level to something like 500 to suppress non json output.

**Did the error occur in between an active task (`download` / `stream` / `grab`)?**

This focus on grab command.

This indicates if the scraper or program is broken totally or the scraper or program may have a few issues on the inside.

**Screenshots [Optional]**

**Additional information**
- animdl version: 1.6.20

> animdl grab -ll 500 --index 1 "Black Lagoon"
                                                                justfoolingaround/animdl - v1.6.20                                                                 
                                                       A highly efficient, powerful and fast anime scraper.                                                        
                                                       {"episode": 1, "streams": [{"stream_url":                                                   "https://v.vrv.co/evs3/eb3375df2a9a3e59d5517104ac8bd068/assets/aeefb0f95068e260e836c8088850c054_,4481191.mp4,4481192.mp4,4481190.mp4,4481189.mp4,4481188.mp4,.urlset/master.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly92LnZydi5jby9ldnMzL2ViMzM3NWRmMmE5YTNlNTlkNTUxNzEwNGFjOGJkMDY4L2Fzc2V0cy9hZWVmYjBmOTUwNjhlMjYwZTgzNmM4MDg4ODUwYzA1NF8sNDQ4MTE5MS5tcDQsNDQ4MTE5Mi5tcDQsNDQ4MTE5MC5tcDQsNDQ4MTE4OS5tcDQsNDQ4MTE4OC5tcDQsLnVybHNldC9tYXN0ZXIubTN1OCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY1OTMxMjQzNH19fV19&Signature=JGrceqoLtJ1KGcbnXDDgXXhAMOBAAx1GZL8X00o6yZIIes44dRJiFn9IE-cpjRHwuYGczfgnQPcLIYYDeUku5MCxuIV~Da46oOorBVVincdrZvx03Y18-T6a-AnMXkGTyFfiJKUUpUggqdW1T7oKvSoFEJEH-cVLal0kTIuliqYw2bkfkGFqZT6v4ZOlPSYROFCS9TuZRHl5Ylf2OuIu6bbns4naos8dBWVexYGjknrXB3ZExcxvyXP~-G8uulg5Y6HxPZE5b2erhz9w2L~P1J2ttXlVeOBKjOdPP6I06Fqwa7QFxdknqeNYK63MmbOc7LOlARX610~5GRl3gHvkRg__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA"}]}

**Comment by justfoolingaround** [comment]
Fixed (well, I commented somewhere else my bad!), hence closed.
