### ISSUE TITLE
Animxplay mega source not scraped 

### ISSUE THREAD

**Issue by zezo357** [justfoolingaround/animdl#170]
**Describe the bug**

animxplay when an episode is uploaded like 30 mmiuntes ago the source will be mega 
example from website html is 
```
"6":"https://mega.nz/embed/WD4XFQDD#Utyvsx4AicLnEQ5AxAzlgiwqIKEJkD3d6ZfhY-PGs3A"
```

 

and the scraper doesnt get a link for it 

**Did the error occur in between an active task (`download` / `stream` / `grab`)?**
all of them

**Screenshots [Optional]**
![image](https://user-images.githubusercontent.com/25157308/183432539-976d188c-0f1a-422f-83c6-19d4b073b82b.png)

**Additional information**
- v1.6.21
- animixplay.to

**Comment by justfoolingaround** [comment]
Which anime does this? 

This is because a Mega extractor hasn't yet been added and it could potentially be impossible since it has chunked encryption on downloads.

**Comment by zezo357** [comment]
https://animixplay.to/v1/tensei-kenja-no-isekai-life-dai-2-no-shokugyou-wo-ete-sekai-saikyou-ni-narimashita/ep7

that is the anime but now its converted to 
"6":"//goload.io/streaming.php?id=MTkwMjgy&title=Tensei+Kenja+no+Isekai+Life%3A+Dai-2+no+Shokugyou+wo+Ete%2C+Sekai+Saikyou+ni+Narimashita+Episode+7"

and that works well in your code 

if mega can be added i would love it 

thank you for the awesome repo♥

**Comment by zezo357** [comment]
@justfoolingaround 
i am sorry for the mention

but i wanted to ask 
`it has chunked encryption on downloads.`

that means players like vlc will fail to play it too?

or only downloader will fail?

**Comment by justfoolingaround** [comment]
Basically, direct playback wouldn't work.

Downloading with a custom downloader will work: the one used by Mega over their site itself.

To make both work robustly, a webserver which would return the decrypted content through sent parameters would be required.

**Comment by zezo357** [comment]
So basically it will require another api to decrypt content of files
And that is outside the scope of this project from my understanding


(question: doesn't mega provide decryption key and value of the encrypted content ) like how m3u8 files does?

**Comment by justfoolingaround** [comment]
Decryption is not a problem at all. I can deal with cryptography. It is just that a webserver would defeat the light-weight factor of the project itself.

It is implementable as an optional feature which would include Flask.

**Comment by zezo357** [comment]
Yeah i get that making a web worker/ api will make the package slower (at least in that case)


But what I don't get is why we need it 😃  if decryption can be made using python (flask) why it won't work in your code? 


I am sorry if I am wasting your time, but I am trying to understand because maybe I can help with it

**Comment by justfoolingaround** [comment]
Sorry for the extremely late response.

This is always possible without an external dependency. However, animdl as a project needs to remain robust. Downloading from Mega would require a custom download algorithm. Flask or any webserver would be ideal as we would be able to simply send decrypted bytes from localhost and treat it like a normal download.

The current project structure would not be suitable for Mega.
