### ISSUE TITLE
Get schedule for today 

### ISSUE THREAD

**Issue by UtkarshVerma** [justfoolingaround/animdl#171]
**Is your feature request related to a problem? Please describe.**
I usually watch currently airing anime and I don't remember which anime airs on which day. Therefore, what I usually do is open a streaming website and see what aired on that day. And then I simply open something I find worth watching.

animdl has done a really good job of streaming anime. However, since I don't know which new anime aired, I end up opening another website just to find out what to watch.

**Describe the solution you'd like**

I feel the `schedule` flag is the solution for me but currently, it only fetches anime which are going to be aired. I would like to be able to know if a new episode came out for an anime I'm currently watching.

Therefore, having a CLI flag for showing me today's anime would be really helpful.

A much better solution for this would be to allow users to specify anime titles (through some file maybe) and have a subcommand which would simply show when these anime are going to be aired next. This would be mimicking the "Currently Watching" section of MyAnimeList.

All in all, these are just my ideas and it is completely up to the dev to decide if it is worth their time.

**Comment by justfoolingaround** [comment]
Added as an offset flag for `schedule`. You can now see aired anime from past 24 hours by default.
