### ISSUE TITLE
stream command not working

### ISSUE THREAD

**Issue by shadow5013** [justfoolingaround/animdl#18]
Hi. I am using Linux. mpv is installed and is in the PATH. Yet the stream command is not working. It works with `animdl_config.json` in the working directory though.

**Comment by justfoolingaround** [comment]
Aight, that was because it looked for `mpv.exe` in the Linux PATH which didn't work as it was an Windows executable.

Should be fixed now!

**Comment by shadow5013** [comment]
Great. Now it works perfectly. Keep it up.
