### ISSUE TITLE
gogo anime doesnt download

### ISSUE THREAD

**Issue by zezo357** [justfoolingaround/animdl#183]
gogo anime can not be downloaded while providing headers 

**Screenshots [Optional]**
# with headers
![image](https://user-images.githubusercontent.com/25157308/193424599-9ae0b010-d5b2-468d-a779-00a0c9b410d0.png)
# without headers 
![image](https://user-images.githubusercontent.com/25157308/193424610-0ce70ff0-10e5-4ab4-a10f-0af5833d0ca4.png)

**Additional information**
- animdl, version 1.6.24
- gogoanime

**Comment by justfoolingaround** [comment]
Fixed as of 1.6.25.
