### ISSUE TITLE
search results animxplay are not easy

### ISSUE THREAD

**Issue by zezo357** [justfoolingaround/animdl#184]
the search results are not accurate (maybe case sensitive) since in some times search doesnt work

**Did the error occur in between an active task (`download` / `stream` / `grab`)?** all

This indicates if the scraper or program is broken totally or the scraper or program may have a few issues on the inside.
search issue only 

**Screenshots [Optional]**
as you can see i can only find the anime if i provided most of the name
![image](https://user-images.githubusercontent.com/25157308/193425085-f8e95dfd-c670-443e-a412-7328fe6e960b.png)

**Additional information**
animdl, version 1.6.24
i think animxplay

**Comment by justfoolingaround** [comment]
Fixed as of 1.6.25.
