### ISSUE TITLE
Use `%appdata%/animdl` config directory and avoid clutter in `%userprofile%` for Windows

### ISSUE THREAD

**Issue by rollingmoai** [justfoolingaround/animdl#185]
> From maintainers: Both labels have been handed to this issue, remove the inapplicable one. Your title should answer at least 3 of 5W1H questions for fastest responses.

**Is your feature request related to a problem? Please describe.**

In Linux, the `.config` directory is used, following the XDG spec. The same should apply to Windows. `%userprofile%` should not be used, and the standard of putting the config directory to `%appdata%` should be used. 

**Describe the solution you'd like**

The config directory should be located to `%appdata%\animdl` instead.

To accommodate this new change, there should be at least two ways of handling the legacy directory (`%userprofile%\.animdl`):

1. Support the old directory. However, `%appdata%\animdl` takes priority if it exists and `%userprofile%\.animdl` is ignored. Or,
2. Seamless, automatic migration from `%userprofile%\.animdl` to `%appdata%\animdl`.

**Describe alternatives you've considered**

None.

**Additional context**

**Comment by omaru-ok** [comment]
i consider . `.config/animdl ` is good option . but it does not work for me 😔 
 
i can't get animdl-conf workign in window ,  and i dont want to  put `.animdl ` in  `home` directory `home/.animdl` <-- this make home dir a bit clunky :(

**Comment by justfoolingaround** [comment]
As of 1.6.25, a new configuration file has been specified that solves this.

The configurations for Windows should now be at `%LOCALAPPDATA%/,config/animdl/config.yml` similar to the Linux spec.

**Comment by h4rldev** [comment]
The difference between %APPDATA% and %LOCALAPPDATA% are subfolders due to Microsoft stupidity. %APPDATA% refers to "AppData\Roaming", while %LOCALAPPDATA% refers to "AppData\Local"

**Comment by h4rldev** [comment]
It shouldn't really matter where it's stored, as long as people who are capable of editing a text file can access it. (Impossible)
