### ISSUE TITLE
[Feature Request] Passing options to mpv

### ISSUE THREAD

**Issue by shadow5013** [justfoolingaround/animdl#19]
It would be very useful to be able to pass options to mpv. For instance, it is possible to play video without x server with `--vo=drm`  etc.

**Comment by justfoolingaround** [comment]
Added that option in the config. The new config for player would look like:
```json
{
    "players": {
        "mpv": {
            "executable": "mpv",
            "opts": [],
        },   
    }
}
```

**Comment by shadow5013** [comment]
It works. But it would be nice to also have something like `--player-opts "options here"` for temporary options.

**Comment by justfoolingaround** [comment]
Passing options, multiple at that, would be difficult with that method (for the user). The quotes would require to be escaped and it'd be a hassle anyway. In my opinion, modifying the config would be the only reasonable and simpler way.

**Comment by shadow5013** [comment]
Firstly, the quotes wouldn't require to be escaped. Everything inside quotes will be passed as an argument of `--player-opts`. Quotes just preserve the literal value of each character. In other words, everything inside quotes is escaped. Here is the result of a test where i tried to echo the arguments of `player-opts`
``` 
$ python cli.py --player-opts "--vo=gpu --gpu-context=drm"
--vo=gpu --gpu-context=drm
```
You can just parse opts from configuration file, concatenate it with opts from `--player-opts` and then pass it to mpv. 

Secondly, modifying the config file is fine for permanent options. But it'd rather be hassle for one-time options. Hope you can understand.

**Comment by justfoolingaround** [comment]
Alright, I've added the `player-opts` to `stream`. The format however is not `--player-opts "--vo=gpu --gpu-context=drm"`, it is a much simpler `--player-opts "--vo=gpu" "--gpu-context=drm"` and yes, it is appended to the default args (args in the config of course.)

**Comment by shadow5013** [comment]
There might be a problem with parsing.
```bash
./animdl.py stream 'jujutsu' --player-opts "--speed=1.5" "--mute=yes"
░█████╗░███╗░░██╗██╗███╗░░░███╗██████╗░██╗░░░░░
██╔══██╗████╗░██║██║████╗░████║██╔══██╗██║░░░░░
███████║██╔██╗██║██║██╔████╔██║██║░░██║██║░░░░░
██╔══██║██║╚████║██║██║╚██╔╝██║██║░░██║██║░░░░░
██║░░██║██║░╚███║██║██║░╚═╝░██║██████╔╝███████╗
╚═╝░░╚═╝╚═╝░░╚══╝╚═╝╚═╝░░░░░╚═╝╚═════╝░╚══════╝v1.3.0
A highly efficient anime downloader and streamer

Usage: animdl.py stream [OPTIONS] QUERY
Try 'animdl.py stream --help' for help.

Error: no such option: --mute
```

**Comment by justfoolingaround** [comment]
So, the `click.options` with `multiple` works kinda differently than I thought. It works rather with

```sh
animdl.py stream 'jujutsu' --player-opts "--speed=1.5" --player-opts "--mute=yes"
```

than listing the commands one after other. This *is* a bit too weird. If you're fine with this, let me know or I'll just add a regex argument parser that does parsing through a single string.

**Comment by shadow5013** [comment]
A single string would be more convenient.

**Comment by justfoolingaround** [comment]
Aight, done. (Just recalled that click has `shlex.split`, ignore the wrong referencing on the latest commit)

**Comment by shadow5013** [comment]
Working correctly. Thank you.
