### ISSUE TITLE
.animdl(configuration file not found)

### ISSUE THREAD

**Issue by ILARIO-KAGOO** [justfoolingaround/animdl#190]
I have submitted this issue to inform that i wasnt able to find the configuration file nor the .animdl in the location which was mentioned and i even tried searching for it but it says not found

**Comment by NaiveInvestigator** [comment]
Which OS do you use? Or are you using windows?

**Comment by ILARIO-KAGOO** [comment]
i use windows 11

**Comment by ILARIO-KAGOO** [comment]
now its showing that multidict._multilib is not recognised as pacakges

**Comment by ILARIO-KAGOO** [comment]
![image](https://user-images.githubusercontent.com/112496154/200598475-01f5b637-1cfc-442f-b023-f674c7534e0e.png)

**Comment by ILARIO-KAGOO** [comment]
idk how to fix this
although I have vs version above 14.0

**Comment by NaiveInvestigator** [comment]
I'm no dev but I think you need to install [msbuild tools](https://download.visualstudio.microsoft.com/download/pr/5c9aef4f-a79b-4b72-b379-14273860b285/d711c946d1f95bffaba890d7288a9d9c1f1df80208b61bf50b926dd0e2f92f45/vs_BuildTools.exe). Try that and see.

**Comment by ILARIO-KAGOO** [comment]
i did that and thats not the problem here
the problem is python doesnt recognise "multidict._multilib" as a library

**Comment by justfoolingaround** [comment]
Configurations do not generate by themselves. You have to create your own in the specified directory.
