### ISSUE TITLE
Request for implementation of ani-skip feature for auto-skipping opening sequences in animdl

### ISSUE THREAD

**Issue by synacktraa** [justfoolingaround/animdl#201]
As a user of the **animdl**, I am requesting the implementation of a new feature called [**ani-skip**](https://github.com/synacktraa/ani-skip). This feature would allow users to choose whether or not they want to automatically skip the opening sequences of an anime episode when using the **animdl**.

This feature would be especially useful for those who have already watched the opening sequence or simply want to get to the main content of the episode as quickly as possible. It would save users time and make the viewing experience more efficient.

I suggest that this functionality could be accessed using some flag. For example, `animdl -flag` would enable the feature, while `animdl` would disable it. This would allow users to easily toggle the feature on or off as needed.

Thank you for considering this feature request.

**Comment by justfoolingaround** [comment]
I've added ani-skip but it does not quite skip automatically.

In essence, it is added as a chapter provider that is supported by `mpv` based players. 

This feature can be toggled by using `aniskip: true` in the config file. Let me know if there's something more!

**Comment by synacktraa** [comment]
Sure, I will
