### ISSUE TITLE
Building fine, error on running. 

### ISSUE THREAD

**Issue by rares9301** [justfoolingaround/animdl#205]
# Issue on using the client. 
## Machine details
animdl version: 1.6.44
pyhton 3.11
build : both pip & source-code 
## Description 
Updated from 1.6.33 ( lxml wheel workaround version ) to the newest 1.6.44, throwing pkginfo issue. 
`pkginfo` and `packaging` not installed by default.
### Before update
![before-update](https://user-images.githubusercontent.com/76567014/209347966-04cf5f04-c216-43ec-8c11-70fb69c258c0.png)
### Update using "animdl update" + basic command 
![after-update](https://user-images.githubusercontent.com/76567014/209348348-16493a01-b285-4a39-ba57-7c1d566cc5b5.png)
# Workaround found:

**Comment by justfoolingaround** [comment]
Incredibly weird since `pkginfo` was expected to be installed by default anyway.

Try `pip install pkginfo` while this gets resolved.

**Comment by rares9301** [comment]
yeah, installing pkginfo almost fixes the issue. 
Still after you pip install it, you get the "No module named 'packaging' " error.
so i had to also do `pip install pkginfo` , which fixes the issue

**Comment by justfoolingaround** [comment]
Now fixed as of `1.6.46`.
