### ISSUE TITLE
Site request: YugenAnime

### ISSUE THREAD

**Issue by rollingmoai** [justfoolingaround/animdl#208]
From maintainers: Both labels have been handed to this issue, remove the inapplicable one. Your title should answer at least 3 of 5W1H questions for fastest responses.

**Is your feature request related to a problem? Please describe.**

Since Animixplay is down, YugenAnime is recommended as a great Animixplay alternative that can also scrape gogo and vrv.

**Describe the solution you'd like**

Add YugenAnime

**Describe alternatives you've considered**

**Additional context**

https://yugen.to/

**Comment by justfoolingaround** [comment]
Wow, nice find. Will be added soon!

**Comment by justfoolingaround** [comment]
(This was added, I just forgot to inform 💀)
