### ISSUE TITLE
Kamyroll api changes

### ISSUE THREAD

**Issue by toomyzoom** [justfoolingaround/animdl#211]
**Describe the bug**

A clear and concise description of what the bug is. This includes whether the bug wasn't there in previous versions (in which case you're expected to provide a version number.)
Kamyroll provider is broken. Seem like auth/v1/token call to get access token was changed from POST to GET with params instead of post data. It's probably related to this [https://github.com/kamyroll/Kamyroll-Wiki/commit/a3930742f8a4e5d94c3d10ac09a7da5c4390f0e0](https://github.com/kamyroll/Kamyroll-Wiki/commit/a3930742f8a4e5d94c3d10ac09a7da5c4390f0e0)

```
def get_token(self):
...
           response = self.session.get(
                self.API_URL + "auth/v1/token",
                params={
                    "device_id": "web",
                    "device_type": "python.animdl",
                    "access_token": "HMbQeThWmZq4t7w",
                },
            ).json()
```

**Did the error occur in between an active task (`download` / `stream` / `grab`)?**
All commands

This indicates if the scraper or program is broken totally or the scraper or program may have a few issues on the inside.

**Screenshots [Optional]**

**Additional information**
- animdl version: 1.6.55
- The site and provider this issue is related to: kamyroll

**Comment by justfoolingaround** [comment]
Fixed as of `1.7.0`.
