### ISSUE TITLE
Get episodes count

### ISSUE THREAD

**Issue by metafates** [justfoolingaround/animdl#212]
**The inquiry**

Thank you for your work!

Is there any way to get episodes count of a particular anime? I have a script that

1. Runs `animdl search QUERY --json`
2. User selects an anime from search results
3. Run `???` to get episodes count **<-- How do I do this?**
4. User selects an episode
5. Run `animdl grab URL --index INDEX -r EPISODE"

I know that if I run `animdl grab` without `-r` flag it will output all available episodes, but that seems rather slow for the sake of just getting the **number** of episodes, since I don't need to decode stream urls for each

**Comment by justfoolingaround** [comment]
Explained intricacies over Discord so will be closing this.
