### ISSUE TITLE
Hard to read color for choices/titles/urls

### ISSUE THREAD

**Issue by RaitaroH** [justfoolingaround/animdl#214]
From maintainers: Both labels have been handed to this issue, remove the inapplicable one. Your title should answer at least 3 of 5W1H questions for fastest responses.
From me: I cannot remove any label. Nor add.

**Is your feature request related to a problem? Please describe.**

Can you use a different choice/url/title color? It is rather hard to read on some color schemes like mine:

![image](https://user-images.githubusercontent.com/19552720/211872499-d04dce2e-16e0-4487-8627-048d761a31cd.png)

**Describe the solution you'd like**
- maybe have the titles in white
- then the prompt numbers `1/2/3/...` should be the same blue as the numbers in `1. title / url`

**Describe alternatives you've considered**

- blue titles and urls?

**Comment by justfoolingaround** [comment]
Made changes as required as of `1.7.0`.
