### ISSUE TITLE
Kamyroll return urls behind cloudflare. 403 return

### ISSUE THREAD

**Issue by toomyzoom** [justfoolingaround/animdl#215]
**Describe the bug**

A clear and concise description of what the bug is. This includes whether the bug wasn't there in previous versions (in which case you're expected to provide a version number.)
```
def fetch_streams(api: Kamyroll, medias: "list"):
    ...
    hls_response = api.session.get(stream["url"]).text ---> This will fail to return the video m3u8 EXTINF because they behind cloudflare.
```

grab will return empty streams array because of the above even the api call in fetch_streams function returns stream urls. 

` "streams": []`

**Did the error occur in between an active task (`download` / `stream` / `grab`)?**
All

This indicates if the scraper or program is broken totally or the scraper or program may have a few issues on the inside.

**Screenshots [Optional]**

**Additional information**
- animdl version: 1.6.55
- The site and provider this issue is related to: kamyroll
- May need #211 to be corrected first

**Comment by justfoolingaround** [comment]
Fixed as of `1.7.0`.
