### ISSUE TITLE
Site request: Marin (Formerly Tenshi)

### ISSUE THREAD

**Issue by rollingmoai** [justfoolingaround/animdl#216]
From maintainers: Both labels have been handed to this issue, remove the inapplicable one. Your title should answer at least 3 of 5W1H questions for fastest responses.

**Is your feature request related to a problem? Please describe.**

https://tenshi.moe/ has closed, redirecting to their new site https://marin.moe/

**Describe the solution you'd like**

Support Marin

**Describe alternatives you've considered**

**Additional context**

Tenshi site before redirecting to Marin:
![image](https://user-images.githubusercontent.com/75471378/212287470-d130eef0-8102-479e-8ed3-7a86841830a1.png)

**Comment by justfoolingaround** [comment]
Tenshi has been killed off in favor of the waifu Marin. Thanks for reporting this!

**Comment by rollingmoai** [comment]
Please update the readme as well

**Comment by justfoolingaround** [comment]
That'll take a while since I'll have to change the provider benchmarks as
well.
