### ISSUE TITLE
problem with animdl update, conflict with click version

### ISSUE THREAD

**Issue by bachig26** [justfoolingaround/animdl#223]
I have the latest version of click 8.1.3, but while updating the animdl it uninstalls the latest version and installs the 8.0.4 which the animdl updater has.

**Please fix this issue, so the update doesn't uninstall the version if it's higher or lastest than the animdl required version is low.**
````
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
animdl 1.7.2 requires click<8.1.0,>=8.0.4, but you have click 8.1.3 which is incompatible.
````

**Comment by bachig26** [comment]
@justchokingaround I know that the animdl dependency is updated to latest version in the package, this will be resolved but in future if I want a latest version of click and again updating the animdl will change the click version to it's dependency.

so, i'm hoping for an solution, as i don't know how to prevent this from happening.

**Comment by justfoolingaround** [comment]
Should be fine now, as `click` versions have been bumped.

**Comment by justchokingaround** [comment]
no need to thank me :sunglasses:
