### ISSUE TITLE
It's me, AGAIN!

### ISSUE THREAD

**Issue by haj1s** [justfoolingaround/animdl#23]
it just feels like I'm nagging you at this point, but I still get the same issue [(Attachment)](https://imgur.com/e3ENF60)
 
 
 I'm sorry for opening issues again and again, and for not mentioning this earlier 
 
 (also quick note, you forgot to mention the end feature (-e) and the canon one (--canon)  in your readme.md :P)

**Comment by justfoolingaround** [comment]
So, I assume you've used the PIP installed version, that's the stable version which kinda isn't even with this version yet (it'll be updated once a critical bug needs attention, for now this isn't that critical given how rare it is).

For now, you can use `-t` to mention a download folder.

> (also quick note, you forgot to mention the end feature (-e) and the canon one (--canon) in your readme.md :P)

*yeah a bit too lazy for that xd, soon though*

**Comment by haj1s** [comment]
oh, that's alright the   `-t`  is enough for me :), thank you!
