### ISSUE TITLE
Regular Expressions do not seem to work with the -q argument.

### ISSUE THREAD

**Issue by pie-shifted** [justfoolingaround/animdl#230]
So I'm trying to set up a Reg Ex so that it automatically selects a dubbed stream but it ends up asking me to select a stream anyway.

For instance, by using the grab command, I'm certain 2 of the 6  following streams contain the word "Eng" in their `stream_url` attribute.

**Command**:

 ```batchfile
animdl grab "animepahe: Code Geass Fukkatsu no Lelouch" -r 1 --index 1
```

**Output**:
(bottom two streams)

```json
{
  "episode": 1,
  "streams": [
    {
      "quality": "720",
      "stream_url": "https://eu-041.files.nextcdn.org/get/04/10/54d83eed477b32ef60238cd677f41469700b5b5dbad7cc3a928b22e22fd185d6?file=AnimePahe_Code_Geass_-_Fukkatsu_no_Lelouch_-_01_BD_720p_gg.mp4&token=vBJ5EVVYfhw923PNQZeCdg&expires=1675207024"
    },
    {
      "quality": "1080",
      "stream_url": "https://eu-041.files.nextcdn.org/get/04/16/8022e3efdd8231b7aadd3d0fbb64a6f8501fbc395f3275048386792fa1feca3a?file=AnimePahe_Code_Geass_-_Fukkatsu_no_Lelouch_-_01_BD_1080p_gg.mp4&token=KW1iobCvAMbBL6TfQRsS_A&expires=1675207026"
    },
    {
      "quality": "720",
      "stream_url": "https://eu-031.files.nextcdn.org/get/03/12/ded7808a877130695500dc50ce298350715d317a569b9397d13a59d1540365b3?file=AnimePahe_Code_Geass_-_Fukkatsu_no_Lelouch_-_01_BD_720p_MTBB.mp4&token=TIHR2tCiGG6Ifo4oeyfJGA&expires=1675207028"
    },
    {
      "quality": "1080",
      "stream_url": "https://eu-031.files.nextcdn.org/get/03/16/ec643468f3afd6effe6c2f12143fc7eb3e8c6a57402bbc394ae186f4c5eb0ddc?file=AnimePahe_Code_Geass_-_Fukkatsu_no_Lelouch_-_01_BD_1080p_MTBB.mp4&token=1HXK0nFGp0mkZaLrH-awAg&expires=1675207030"
    },
    {
      "quality": "720",
      "stream_url": "https://eu-031.files.nextcdn.org/get/03/15/822afb045e8d50e7b2f2a9fa0cd3292ea9eb3006cc61b7b810e2b8df88db5c10?file=AnimePahe_Code_Geass_-_Fukkatsu_no_Lelouch_Eng_Dub_-_01_BD_720p_MTBB.mp4&token=DgRUoZv3qcIHoFrSRRT89g&expires=1675207032"
    },
    {
      "quality": "1080",
      "stream_url": "https://eu-041.files.nextcdn.org/get/04/10/31a9df3aacba17cf1dd76afc8d640c1c7f0866f790c3f52e78e28a3d2a713ede?file=AnimePahe_Code_Geass_-_Fukkatsu_no_Lelouch_Eng_Dub_-_01_BD_1080p_MTBB.mp4&token=AJo1lBZe3cBxF1nIJQ8HfQ&expires=1675207034"
    }
  ]
}
```

But when I try to match "Dub" on this attribute in order for it to automatically select the best quality dubbed stream, it doesn't work and asks me to select a stream out of all 6.

**Command**:

 ```batchfile
 animdl stream "animepahe: Code Geass Fukkatsu no Lelouch" -r 1 --index 1 -q best[stream_url=r'Eng']
```
**Output**:
![Output](https://i.imgur.com/SoHHML0.png)

Is this a bug or am I doing something wrong?

**Comment by GauravMohla** [comment]
try 

> animdl stream "animepahe: Code Geass Fukkatsu no Lelouch" -r 1 --index 1 -q [stream_url=r'.+ub(.+)1080p.+']

There is a lower somewhere in code

**Comment by justfoolingaround** [comment]
They use `match` so you'd be expected to use `.+?file=.+?Eng_Dub` or equivalent that matches the string from the *beginning*.

**Comment by pie-shifted** [comment]
> They use `match` so you'd be expected to use `.+?file=.+?Eng_Dub` or equivalent that matches the string from the _beginning_.

Thanks, this is the last piece of the puzzle.

For anyone having the same problem in the future, there are three conditions for this parameter to work properly:

- The pattern string gets lowered, so you can't use uppercase characters.
- Pattern needs to match from the beginning.
- You *have* to use single quotes around the pattern, not double.
