### ISSUE TITLE
Tenshi.moe changed to marin.moe

### ISSUE THREAD

**Issue by Arghadatta** [justfoolingaround/animdl#232]
as of january 2023,tenshi.moe has changed to marin.moe ,so animdl can't work with tenshi.
so requesting dev to change the provider url 

**Additional information**
- animdl version* [LATEST]
- The site and provider this issue is related to. [Tenshi.moe]

**Comment by justfoolingaround** [comment]
(Forgot to close this issue when Tenshi was removed for Marin.)
