### ISSUE TITLE
[9anime] Empty name in grab results because of empty data attribute

### ISSUE THREAD

**Issue by innocenzi** [justfoolingaround/animdl#25]
While searching for `re zero`, I found a result without a name, which might be an edge case.

![](https://i.imgur.com/Znnv1M0.png)

After investigation, `data-jtitle` is missing: 

![](https://i.imgur.com/uQb8H9H.png)

You may want to fall back to `innerText`?

**Comment by justfoolingaround** [comment]
Woops, never noticed that. Should be fixed now. (`data-jtitle` -> `text_content()`/`innerText`)
