### ISSUE TITLE
Allanime no subtitles?

### ISSUE THREAD

**Issue by QW60** [justfoolingaround/animdl#252]
**The inquiry**

When I use AllAnime as my stream provider I almost never get subtitles just the plain japanese version without any subtitles. AllAnime does have subs for all the shows I've tried on their site so am I doing something wrong or is Animdl not finding the subs?

Thanks.

**Comment by fishman** [comment]
I'm having the same issue, when mpv starts through animdl there is a delay and then the following appears. I wonder if that is actually the subtitle error.

[file] Cannot open file '': No such file or directory
Failed to open .
Can not open external file .
     Video --vid=1 (*) (h264 1280x720 23.976fps) (3982 kbps)
 (+) Video --vid=2 (*) (h264 1920x1080 23.976fps) (7988 kbps)
     Video --vid=3 (*) (h264 848x480 23.976fps) (1992 kbps)
     Video --vid=4 (*) (h264 640x360 23.976fps) (997 kbps)
     Video --vid=5 (*) (h264 428x240 23.976fps) (499 kbps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz) (128 kbps)
     Audio --aid=2 (*) (aac 2ch 44100Hz) (96 kbps)
     Audio --aid=3 (*) (aac 1ch 22050Hz) (64 kbps)
