### ISSUE TITLE
Value error upon specific episode download attempt

### ISSUE THREAD

**Issue by ContenderEliminated** [justfoolingaround/animdl#270]
Whenever I attempt to download episode 5 of *Re-Kan!* (using the command `animdl download "Re-Kan!" -r 5-13`), after selecting `https://allanime.to/anime/7LBTHRhKq56jPjGkG` from the initial title query, I get the error `ValueError: max() arg is an empty sequence`.

I had previously attempted to download all episodes in one go, but this issue popped up as soon as animdl tried to download the 5th episode (the prior 4 were successful).

As I'm new to animdl, I can't tell whether this is an issue with the site, my config file, or animdl itself.

**Additional information**
- Log with traceback: [animdl-log.txt](https://github.com/justfoolingaround/animdl/files/11609637/animdl-log.txt)
- This is on version 1.7.12.
- My config.yml file consists solely of `quality_string: best[subtitle]`.

**Comment by Shaun-CCGeek** [comment]
This is an issue that has been popping up a LOT lately (I can't speak for the past, I'm a comparatively new user), and I personally have been a victim of this. The easiest solution I've been offered is to use a different provider. Zoro has been working hassle-free for me.

`animdl download "zoro:Re-Kan! -r 5-13` should work, try it out.

**Comment by ContenderEliminated** [comment]
That did the trick, thanks!
