### ISSUE TITLE
Update info, but no update available on PyPI

### ISSUE THREAD

**Issue by Synertry** [justfoolingaround/animdl#272]
**Describe the bug**
Update info is displaying, but no update available on PyPI.
Current version is 1.7.14 on GitHub, but only 1.7.12 is available on PyPI.

**Screenshots [Optional]**
Update info:
![image](https://github.com/justfoolingaround/animdl/assets/60792595/4b6eee65-57fb-4f25-9ee5-8e708fb31e11)

PyPI:
![image](https://github.com/justfoolingaround/animdl/assets/60792595/7e628603-a015-4fc4-b04a-ef135f35cdf5)

**Additional information**
- animdl version: 1.7.12

**Comment by justfoolingaround** [comment]
Messed up big time on this one. I do apologise.
