### ISSUE TITLE
Can't uae animdl

### ISSUE THREAD

**Issue by vikas-vky** [justfoolingaround/animdl#276]
I've got the below error consistently in all my testing. I've tried installing and reinstalling python of versions 3.8.10 and 3.11.0 updated animdl to latest version and even checked in a VM environment and got the same error. My knowledge on the these scripts only extends to install and using them so help me with this

╭─────────────────────────────── Traceback (most recent call last)
────────────────────────────────╮
│ in _run_module_as_main:198                                                                       │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   alter_argv = False                                                                         │ │
│ │         code = <code object <module> at 0x000001B81C6F5730, file                             │ │
│ │                "C:\Users\Vicky\myenv\Scripts\animdl.exe\__main__.py", line 1>                │ │
│ │ main_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\Vicky\myenv\Scripts\animdl.exe\">,                                  │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\Vicky\myenv\Scripts\animdl.exe\">,                                  │ │
│ │                origin='C:\\Users\\Vicky\\myenv\\Scripts\\animdl.exe\\__main__.py'),          │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__': 'C:\\Users\\Vicky\\myenv\\Scripts\\animdl.exe\\__main__.py',  │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\Vicky\\myenv\\Scripts\\animdl.exe\\__pycache__\\__main__.cpython… │ │
│ │                │   're': <module 're' from                                                   │ │
│ │                'C:\\Users\\Vky_OP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\re\\__… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\Vicky\myenv\Scripts\animdl.exe\">,                                  │ │
│ │                origin='C:\\Users\\Vicky\\myenv\\Scripts\\animdl.exe\\__main__.py')           │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ in _run_code:88                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │       cached = 'C:\\Users\\Vicky\\myenv\\Scripts\\animdl.exe\\__pycache__\\__main__.cpython… │ │
│ │         code = <code object <module> at 0x000001B81C6F5730, file                             │ │
│ │                "C:\Users\Vicky\myenv\Scripts\animdl.exe\__main__.py", line 1>                │ │
│ │        fname = 'C:\\Users\\Vicky\\myenv\\Scripts\\animdl.exe\\__main__.py'                   │ │
│ │ init_globals = None                                                                          │ │
│ │       loader = <zipimporter object "C:\Users\Vicky\myenv\Scripts\animdl.exe\">               │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\Users\Vicky\myenv\Scripts\animdl.exe\">,                                  │ │
│ │                origin='C:\\Users\\Vicky\\myenv\\Scripts\\animdl.exe\\__main__.py')           │ │
│ │     pkg_name = ''                                                                            │ │
│ │  run_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object                                         │ │
│ │                "C:\Users\Vicky\myenv\Scripts\animdl.exe\">,                                  │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\Users\Vicky\myenv\Scripts\animdl.exe\">,                                  │ │
│ │                origin='C:\\Users\\Vicky\\myenv\\Scripts\\animdl.exe\\__main__.py'),          │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__': 'C:\\Users\\Vicky\\myenv\\Scripts\\animdl.exe\\__main__.py',  │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\Users\\Vicky\\myenv\\Scripts\\animdl.exe\\__pycache__\\__main__.cpython… │ │
│ │                │   're': <module 're' from                                                   │ │
│ │                'C:\\Users\\Vky_OP\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\re\\__… │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │  script_name = None                                                                          │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│ C:\Users\Vicky\myenv\Lib\site-packages\click\core.py:1130 in __call__                            │
│                                                                                                  │
│ C:\Users\Vicky\myenv\Lib\site-packages\click\core.py:1055 in main                                │
│                                                                                                  │
│ C:\Users\Vicky\myenv\Lib\site-packages\click\core.py:1654 in invoke                              │
│                                                                                                  │
│ C:\Users\Vicky\myenv\Lib\site-packages\click\core.py:1404 in invoke                              │
│                                                                                                  │
│ C:\Users\Vicky\myenv\Lib\site-packages\click\core.py:760 in invoke                               │
│                                                                                                  │
│ C:\Users\Vicky\myenv\Lib\site-packages\click\decorators.py:26 in new_func                        │
│                                                                                                  │
│ C:\Users\Vicky\myenv\Lib\site-packages\animdl\__main__.py:80 in __animdl_cli__                   │
│                                                                                                  │
│    77 │   │   │   │   client.get(                                                                │
│    78 │   │   │   │   │   f"https://raw.githubusercontent.com/{author}/{repository_name}/{bran   │
│    79 │   │   │   │   ).text,                                                                    │
│ ❱  80 │   │   │   ).group(1)                                                                     │
│    81 │   │   │                                                                                  │
│    82 │   │   │   tuplisied_upstream, tuplised_current_version = tuple(                          │
│    83 │   │   │   │   map(int, upstream_version.split("."))                                      │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │          author = 'justfoolingaround'                                                        │ │
│ │          branch = 'master'                                                                   │ │
│ │          client = <httpx.Client object at 0x000001B8204D1350>                                │ │
│ │         console = <console width=120 ColorSystem.TRUECOLOR>                                  │ │
│ │       constants = <module 'animdl.core.cli.helpers.constants' from                           │ │
│ │                   'C:\\Users\\Vicky\\myenv\\Lib\\site-packages\\animdl\\core\\cli\\helpers\… │ │
│ │             ctx = <click.core.Context object at 0x000001B8204E53D0>                          │ │
│ │  disable_update = False                                                                      │ │
│ │        greeting = 'It is 09:51 PM on a [bold red]beautiful[/] Wednesday!'                    │ │
│ │        regexlib = <module 'regex' from                                                       │ │
│ │                   'C:\\Users\\Vicky\\myenv\\Lib\\site-packages\\regex\\__init__.py'>         │ │
│ │ repository_name = 'animdl'                                                                   │ │
│ │    version_file = 'animdl/core/__version__.py'                                               │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Synertry** [comment]
Hi, @vikas-vky this is related to #274
The version checker currently does not work.
Please use the flag -x until it is fixed:
e.g.: `animdl -x stream 'animepahe:oshi no ko'`

**Comment by Samalbert977** [comment]
Hi, I am getting the same error `AttributeError: 'NoneType' object has no attribute 'group'`
*Note : replaced absolute path with relative path in the below logs*
```
animdl search "Naruto"
                                                                 justfoolingaround/animdl v1.7.15                                                                  
Welcome, buddy.
   It is 11:36 PM on a beautiful Wednesday!
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│  <Path>/animdl:8 in <module>                                                     │
│                                                                                                  │
│   5 from animdl.__main__ import __animdl_cli__                                                   │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(__animdl_cli__())                                                               │
│   9                                                                                              │
│                                                                                                  │
│ ╭─────────────────────── locals ───────────────────────╮                                         │
│ │  re = <module 're' from '/usr/lib/python3.10/re.py'> │                                         │
│ │ sys = <module 'sys' (built-in)>                      │                                         │
│ ╰──────────────────────────────────────────────────────╯                                         │
│                                                                                                  │
│ ~/.local/lib/python3.10/site-packages/click/core.py:1130 in __call__                  │
│                                                                                                  │
│ ~/.local/lib/python3.10/site-packages/click/core.py:1055 in main                      │
│                                                                                                  │
│ ~/.local/lib/python3.10/site-packages/click/core.py:1654 in invoke                    │
│                                                                                                  │
│ ~/.local/lib/python3.10/site-packages/click/core.py:1404 in invoke                    │
│                                                                                                  │
│ ~//.local/lib/python3.10/site-packages/click/core.py:760 in invoke                     │
│                                                                                                  │
│ ~/.local/lib/python3.10/site-packages/click/decorators.py:26 in new_func              │
│                                                                                                  │
│ ~/.local/lib/python3.10/site-packages/animdl/__main__.py:80 in __animdl_cli__         │
│                                                                                                  │
│    77 │   │   │   │   client.get(                                                                │
│    78 │   │   │   │   │   f"https://raw.githubusercontent.com/{author}/{repository_name}/{bran   │
│    79 │   │   │   │   ).text,                                                                    │
│ ❱  80 │   │   │   ).group(1)                                                                     │
│    81 │   │   │                                                                                  │
│    82 │   │   │   tuplisied_upstream, tuplised_current_version = tuple(                          │
│    83 │   │   │   │   map(int, upstream_version.split("."))                                      │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │          author = 'justfoolingaround'                                                        │ │
│ │          branch = 'master'                                                                   │ │
│ │          client = <httpx.Client object at 0x7f0a8504b6d0>                                    │ │
│ │         console = <console width=163 ColorSystem.EIGHT_BIT>                                  │ │
│ │       constants = <module 'animdl.core.cli.helpers.constants' from                           │ │
│ │                   '~/.local/lib/python3.10/site-packages/animdl/core/cli/helpers… │ │
│ │             ctx = <click.core.Context object at 0x7f0a84f78cd0>                              │ │
│ │  disable_update = False                                                                      │ │
│ │        greeting = 'It is 11:36 PM on a [bold red]beautiful[/] Wednesday!'                    │ │
│ │        regexlib = <module 'regex' from                                                       │ │
│ │                   '~/.local/lib/python3.10/site-packages/regex/__init__.py'>      │ │
│ │ repository_name = 'animdl'                                                                   │ │
│ │    version_file = 'animdl/core/__version__.py'                                               │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by vikas-vky** [comment]
> Hi, @vikas-vky this is related to #274 The version checker currently does not work. Please use the flag -x until it is fixed: e.g.: `animdl -x stream 'animepahe:oshi no ko'`

**Comment by vikas-vky** [comment]
> Hi, @vikas-vky this is related to #274 The version checker currently does not work. Please use the flag -x until it is fixed: e.g.: `animdl -x stream 'animepahe:oshi no ko'`

It's working thankyou
