### ISSUE TITLE
Falling back to mirrors due to an unexpected error: Max tries exceeded with the given provider mirror..

### ISSUE THREAD

**Issue by shahrier-nafis** [justfoolingaround/animdl#28]
**animdl download  "dragon ball dub" --idm**
Every thing was fine but after 19th download this started to showing up , 

[animdl-9anime-warning] Falling back to mirrors due to an unexpected error: Max tries exceeded with the given provider mirror..
[animdl-9anime-warning] If the problem persists, feel free to raise an issue with the anime url and episode number immediately.
[animdl-9anime-warning] Falling back to mirrors due to an unexpected error: Max tries exceeded with the given provider mirror..
[animdl-9anime-warning] If the problem persists, feel free to raise an issue with the anime url and episode number immediately.
[animdl-9anime-warning] Falling back to mirrors due to an unexpected error: Max tries exceeded with the given provider mirror..
[animdl-9anime-warning] If the problem persists, feel free to raise an issue with the anime url and episode number immediately.
[animdl-9anime-warning] Falling back to mirrors due to an unexpected error: Max tries exceeded with the given provider mirror..
[animdl-9anime-warning] If the problem persists, feel free to raise an issue with the anime url and episode number immediately.
[animdl-9anime-downloader-core] Failed to download 'E20' due to lack of stream urls.
[animdl-9anime-warning] Falling back to mirrors due to an unexpected error: Max tries exceeded with the given provider mirror..
[animdl-9anime-warning] If the problem persists, feel free to raise an issue with the anime url and episode number immediately.
[animdl-9anime-warning] Falling back to mirrors due to an unexpected error: Max tries exceeded with the given provider mirror..
[animdl-9anime-warning] If the problem persists, feel free to raise an issue with the anime url and episode number immediately.
[animdl-9anime-warning] Falling back to mirrors due to an unexpected error: Max tries exceeded with the given provider mirror..
[animdl-9anime-warning] If the problem persists, feel free to raise an issue with the anime url and episode number immediately.
[animdl-9anime-warning] Falling back to mirrors due to an unexpected error: Max tries exceeded with the given provider mirror..
[animdl-9anime-warning] If the problem persists, feel free to raise an issue with the anime url and episode number immediately.
[animdl-9anime-downloader-core] Failed to download 'E21' due to lack of stream urls.
[animdl-9anime-warning] Falling back to mirrors due to an unexpected error: Max tries exceeded with the given provider mirror..
[animdl-9anime-warning] If the problem persists, feel free to raise an issue with the anime url and episode number immediately.
[animdl-9anime-warning] Falling back to mirrors due to an unexpected error: Max tries exceeded with the given provider mirror..
[animdl-9anime-warning] If the problem persists, feel free to raise an issue with the anime url and episode number immediately.
[animdl-9anime-warning] Falling back to mirrors due to an unexpected error: Max tries exceeded with the given provider mirror..
[animdl-9anime-warning] If the problem persists, feel free to raise an issue with the anime url and episode number immediately.
[animdl-9anime-warning] Falling back to mirrors due to an unexpected error: Max tries exceeded with the given provider mirror..
[animdl-9anime-warning] If the problem persists, feel free to raise an issue with the anime url and episode number immediately.
[animdl-9anime-downloader-core] Failed to download 'E22' due to lack of stream urls.
[animdl-9anime-warning] Falling back to mirrors due to an unexpected error: Max tries exceeded with the given provider mirror..
[animdl-9anime-warning] If the problem persists, feel free to raise an issue with the anime url and episode number immediately.
[animdl-9anime-warning] Falling back to mirrors due to an unexpected error: Max tries exceeded with the given provider mirror..

**Ctrl + c**

then , **animdl download  "dragon ball dub" --idm -s 20**

downloaded ep 20 then again , 
downloading 1 ep and going like that

**Comment by shahrier-nafis** [comment]
and also I cancelled on ep 14 once

**Comment by shahrier-nafis** [comment]
and I also set download progress dialog start view to [minimized to system ] and dilsabeled complete dilog , but now I turned them on and its working again . So mybe that's it then 😅.

**Comment by justfoolingaround** [comment]
Nah, it seems like a problem related to a unstable internet connection.
 Unfortunately not much can be done if none of the sources throw stream links. It is irreproducible too hence there's no way for me to "fix" this issue :/.

**Comment by shahrier-nafis** [comment]
but my internet connection is stable enough , 500kb/s , and it grabs link without any problem and fast. But it's happening again ,just downloading 1 ep then this error, maybe its something else.

**Comment by justfoolingaround** [comment]
This problem starts soon as the internet disconnects from `animdl`. Grabbing has nothing to do with this, ironically, it proves that over a period of lesser time, extraction does not throw error suggesting that, over an extended period, such issue is seen.

**Comment by shahrier-nafis** [comment]
**ooo,
so anyway I'm using a .bat file** 

@echo off
set countfiles=100
:loop
set /a countfiles -= 1

animdl continue

if %countfiles% GTR 0 goto loop

pause
