### ISSUE TITLE
anime from another episode

### ISSUE THREAD

**Issue by StoreyedJoker72** [justfoolingaround/animdl#289]
how do i set it to so like i am downloading attack on titan and now i want to start it from episode 9 but its starting from 1 and overwriting i guess....

**Comment by nattadasu** [comment]
Set `--range`/`-r` in your `download` prompt. See [`-r`/`--range` argument](https://github.com/justfoolingaround/animdl#-r----range-argument).

For example:

```bash
# Only download ep 9
animdl download -r "9" "Attack on Titan"

# Download from ep 9 to 12
animdl download -r "9-12" "Attack on Titan"
```

**Comment by StoreyedJoker72** [comment]
THX!!!!!
