### ISSUE TITLE
Gogoanime has change to a new domain

### ISSUE THREAD

**Issue by GeoTech7515** [justfoolingaround/animdl#294]
![image](https://github.com/justfoolingaround/animdl/assets/21181898/7a323305-d4d0-4f9a-b2a7-dbafc3f3002c)

**Comment by Asik007** [comment]
believe this is the reason why when using gogoanime as a default provider it just prints `Waiting for you to select a 'search result'.
Could not find an anime of that name :/.`

**Comment by crxssed7** [comment]
This is fixed in #296
