### ISSUE TITLE
TS done downloading but doesn't match the filesize

### ISSUE THREAD

**Issue by ajam123** [justfoolingaround/animdl#30]
I tested out downloading another .ts today and looks like it downloaded 350MB as shown in the console but after it finished, saw it like only 60-80MB and the quality is 360p.

**Comment by justfoolingaround** [comment]
HLS downloads don't show what the total download file size is. 

Let me explain what a HLS stream is. So assume there's a playlist of music that you're going to download. There's no given information about the file size and content type; the only thing there is the stream urls to those music. Hence, getting the file size during a batch download would be impossible (it is possible but incredibly inefficient) as each of those music could vary in size. 

`animdl` downloads video streams from HLS playlists and compiles it all together. You see "`1ts/s`" in the progress bar, that is, it's  downloading one such stream per second. There maybe 100s of such streams that require to be downloaded sequentially.

So, even if it says 1/350 in the progress bar, it doesn't mean it is 350 MB. It sometimes is 60~80 MB. This *might* seem like a concern but it isn't.

_HLS streams are hence, only good for streaming and not for downloading. I added this feature on excessive demand, even though it is highly inefficient to do so._
