### ISSUE TITLE
[Feature request] Anime episodes grab range

### ISSUE THREAD

**Issue by innocenzi** [justfoolingaround/animdl#32]
So, if you try `animdl grab https://9anime.to/watch/one-piece.ov8`, you'll have to wait for a long time. 430 episodes took me 8 min 45, and there are more.

I'd imagine something like `animdl grab https://9anime.to/watch/one-piece.ov8 --from=0 --to=10`, so I can loop through that call with short lived processes until there is no more episodes.

Would something like this be possible to implement?

**Comment by justfoolingaround** [comment]
`--start`/`-s` and `--end`/`-e` already exist for that purpose.

**Comment by innocenzi** [comment]
I've no clue how I missed that, my bad.
