### ISSUE TITLE
Using grabed links in jdownloader

### ISSUE THREAD

**Issue by shahrier-nafis** [justfoolingaround/animdl#33]
add a tag in grabed links so I can use jdownloader packagizer to rename all the files.

**like this :** 
[E14] {"episode": 14, "streams": [{"quality": "1080", "stream_url": "https://www12.mp4upload.com:282/d/q6x5hfomz3b4quuobgxropcfklud4j4b3i5v7x2zbhxtpkcpmljmcyzc/video.mp4                **?ep=e14**                     ", "headers": {"referer": "https://www.mp4upload.com/embed-mnesle1izzy0.html", "ssl_verification": false}}]}

**Comment by justfoolingaround** [comment]
Won't be added. 

The thing you're calling a "tag" is actually a query parameter used to request the content off of a site. This may work for some video streams but will not for others. There's no way I'm risking the whole stream url system to throw 404 over a query parameter, going to be used externally at that.

I'm sorry lol. For compensation, I also looked through methods to integrate JDownloader with animdl which seems to be impossible without JDownloader hosting a webserver.
