### ISSUE TITLE
Request - Able to change download's host.

### ISSUE THREAD

**Issue by ajam123** [justfoolingaround/animdl#35]
Not sure if this already exists or not. 

I was wondering if we can make that we able to select/change or keep our server host from like the current one (google APIs I guess?) to like VidStream, MP4Upload, or something similar.

**Comment by justfoolingaround** [comment]
Could be considered if there were multiple sources with multiple hosts. Currently only 9Anime has this implemented.

I'll re-open this in the future when there are multiple sources with multiple hosts and this needs to be added.

For 9Anime, the fallback is: `mp4upload` -> `streamtape` -> `vidstream` -> `mycloud`

VidStream is pretty much Google APIs.

*GGA may have multiple quality on site but it hasn't been implemented with the code and I don't plan to either.*
