### ISSUE TITLE
Backwards compatibility issue of executable

### ISSUE THREAD

**Issue by Justaus3r** [justfoolingaround/animdl#36]
hey!,here for reporting a quick issue
So yeah i think i forgot to tell ya that since python3.9,windows 7 and older are not supported.so obviously executable created using python 3.9 is also not supported on windows 7.a friendly advice is that you should use python 3.8,but if you don't want to use python3.8,then create a portable installation of python3.8 for building your project.also i presume that you are using the ```--onefile``` flag to create an executable.while you can create a single standalone.it is not encouraged by the author and personally too.this feature is in alpha stages and creates many problems.i advice you to use the --standalone flag instead of it.a folder will be created with name ```yourproject.dist``` and all the files inside it will be needed to run your binary file but its alot faster(since it doesn't need to unpack to a temp directory) and preferable.but if you want to create a single standlone then pyinstaller is the best choice.it will pack your program into one executable but the speed is slow(sometimes very slow). 

regards,

**Comment by justfoolingaround** [comment]
For now, I took the second suggestion of using `--standalone`. I will kinda utilize Python 3.8 on the future releases. _(Kinda have to install it and yeah I'm a bit busy myself)_

**Comment by justfoolingaround** [comment]
Aight so the automatic release takes place [here](https://github.com/justfoolingaround/animdl/releases/tag/1.3-auto) which is Python 3.6. Hence, I assume the executable will now be backward compatible.

**Comment by Justaus3r** [comment]
Yeah, i see you have set workflows for automatically reproducing binaries.while this will automate all the release stuff and relief you from headache a producing binaries yourself,it could be problematic as nuitka is still not very stable.i guess what i mean is even adding a single module can cause problems sometimes(happened to me many times).*WELL* i don't think its much of a problem as you could always re-upload the problematic release manually so yeah..
