### ISSUE TITLE
Plz add aria2 support 

### ISSUE THREAD

**Issue by Navid906** [justfoolingaround/animdl#37]
Hls download which use in the program is really slow for me. Can you plz just add aria2 support. Plz.
Thanks for the good work.

**Comment by justfoolingaround** [comment]
I can add aria2 support but ... It doesn't support HLS downloading. Also, currently all the sources except Animixplay use high speed MP4 and even Animixplay has high speed HLS downloading.

 Can you let me know what is it that you're downloading?

**Comment by justfoolingaround** [comment]
Since aria2 wouldn't resolve any issues related to downloading nor be any faster. I've resorted to not add aria2 for the time being.
