### ISSUE TITLE
Downloaded video saved in .php instead.

### ISSUE THREAD

**Issue by ajam123** [justfoolingaround/animdl#38]
Not sure what happen, but you can see in the picture.

Downloading Fairy Tail: Final Series via GGA provider.

![Screenshot 2021-07-17 172741](https://user-images.githubusercontent.com/23212807/126032668-21926430-fe84-4d54-94fa-a2c94fa15ead.png)

**Comment by ajam123** [comment]
seems like it happened to every anime I tried to download.

**Comment by justfoolingaround** [comment]
Which version are you using? (Just see the "banner" when launching animdl)

**Comment by ajam123** [comment]
ah shesh, i was using older, updating it to newest fixed it. thanks

**Comment by justfoolingaround** [comment]
lol no worries. Also changing the file extension from PHP to MP4 will make the previous "PHP" file fixed as that was just a file extension missassignment bug.
