### ISSUE TITLE
Sudden "Failed to download due to lack of stream urls."

### ISSUE THREAD

**Issue by ajam123** [justfoolingaround/animdl#40]
I suddenly have this problem, not sure what happened. It happened to all anime I tried to download, no matter what anime it is.

The provider is GGA.

**Comment by justfoolingaround** [comment]
Aight, so they've changed their stream link mechanism to an encrypted one.

This will be resolved once I reverse their mechanism. Until then, I suggest using other alternatives. I'm sorry that you needed to face this issue.

**Comment by justfoolingaround** [comment]
And fixed! It'll roll out to the stable version soon!
