### ISSUE TITLE
Quality Links not working

### ISSUE THREAD

**Issue by NavDevP** [justfoolingaround/animdl#46]
Actually, I'm grabbing from gogo but quality links not working so I fixed it. Please Reply!! I want to tell you that fix. 
Thank you for making such a good extension

**Comment by justfoolingaround** [comment]
Yep, I'd like to know that fix!

**Comment by NavDevP** [comment]
on FILE ---->  providers/gogoanime/__init_.py > line 52  >>>

 with session.get(url,headers={'referer':'https://streamani.net/'}) as server_load:

just add referer https://streamani.net/

by adding this referer I'm able to get the m3u8 URL working. Thanks

**Comment by justfoolingaround** [comment]
Aight so it took me an hour because your method actually helped me realize that I can scrape all the MP4s provided by GogoAnime with ease.

Thanks to this, you get a massive multi-quality selection now, in which all the links are mp4s

Thanks a lot !!

**Comment by justfoolingaround** [comment]
If you're wondering how insane of a upgrade this is:
![image](https://user-images.githubusercontent.com/79979949/129603893-e6d32df3-ebf7-4d0c-9727-00c6fadc7521.png)

**Comment by NavDevP** [comment]
Glad you like it. 😊
