### ISSUE TITLE
[Feature Request] Animdl as a Module

### ISSUE THREAD

**Issue by shadow5013** [justfoolingaround/animdl#49]
I was trying to write a script to workaround the previous issue and parsing output from `grab` was really hard. It would be nice to be able to use animdl as a module. Also, the `--quite` option from #24 is not working.

**Comment by justfoolingaround** [comment]
`--quite` option has been modified to log levels. Use `-ll 500` or something higher than 110 to get rid of any logger calls!

Also, use `search` with `--json` to get stream links forehand, passing stream links directly will remove any selection prompts.
