### ISSUE TITLE
New Quality Links not Working After Fix.

### ISSUE THREAD

**Issue by NavDevP** [justfoolingaround/animdl#50]
After improving the quality links. it's giving me **302 redirect** to another URL. 

And after the redirect that URL is not working?

That URL giving me 403 Error!

Can you please help me figure it out :)

**Comment by justfoolingaround** [comment]
Is that happening with animdl? I just tested it and it gave me the appropriate stream url.

If it is unrelated with animdl, keep in mind you need a referer header for getting an access to the stream urls.

**Comment by NavDevP** [comment]
im trying to play it on hls player but its giving me 403 error even after applying referer

**Comment by justfoolingaround** [comment]
Can you give me the stream url for reference?

**Comment by NavDevP** [comment]
`https://cdn18.anicdn.stream/user1342/b0449575ee534290ce7781101038f64f/EP.1.1080p.mp4?token=2Ltbkx5-vCGcuN_mQqnwLQ&expires=1629711470&id=68608`

When i try to play this on hls player it gives me 403 error?

**Comment by mnabid** [comment]
Using `https://anicdn.stream` as referer works.

**Comment by NavDevP** [comment]
> Using `https://anicdn.stream` as referer works.

Where did you try this?

on which player?

**Comment by mnabid** [comment]
I tried on **MX Player Pro (android)** and **mpv (linux)**, works on both players.

Try this-

```bash
mpv --referrer="https://anicdn.stream" "https://cdn18.anicdn.stream/user1342/b0449575ee534290ce7781101038f64f/EP.1.1080p.mp4?token=iUCCpGggNHvMCfao3F7Wvg&expires=1629776812&id=68608"
```
or

```bash
mpv --referrer="https://gogo-cdn.com" "https://cdn18.anicdn.stream/user1342/b0449575ee534290ce7781101038f64f/EP.1.1080p.mp4?token=iUCCpGggNHvMCfao3F7Wvg&expires=1629776812&id=68608"
```

**Comment by justfoolingaround** [comment]
Yeah as @mnabid says, it should be an issue regarding the referer headers. `animdl` wouldn't face this issue because it uses a redirect url as the stream url from `https://gogo-cdn.com/` which automatically becomes a referer during use.

**Comment by NavDevP** [comment]
Ok I've tested on VLC and its working fine but when trying to play in android it gives --> 
`Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403`

**Comment by mnabid** [comment]
Maybe an user agent issue...or ExoPlayer isn't getting the referer properly.
Or...[maybe a problem with ExoPlayer itself...?](https://github.com/google/ExoPlayer/issues/5911#issuecomment-500800042) ¯\\\_(ツ)\_/¯

I don't know anything about ExoPlayer though. Found [this](https://stackoverflow.com/questions/31162441/setting-headers-for-streaming-mp4-video-and-playing-files-with-exoplayer) stackoverflow thread, might be helpful.

Since `animdl` *officially* only supports mpv and VLC, it shouldn't be an issue on those players.

**Comment by NavDevP** [comment]
Oh sorry, Thanks for the Satckoverflow Url. It's good now. Thank you for your Support.
Now I'm Closing this issue :)
