### ISSUE TITLE
Animepahe not working

### ISSUE THREAD

**Issue by shadow5013** [justfoolingaround/animdl#53]
kwik.cx have changed the URI structure of the contents. They have replaced the `-` before `files` with `.` (i.e. `https://eu-d4.files.nextcdn.org/` instead of `https://eu-d4-files.nextcdn.org/`). Please update animdl accordingly.

**Comment by justfoolingaround** [comment]
Thanks for helping me identify this lol.

My IP has probably been blacklisted by DDoS guard due to which I couldn't check what was wrong myself.
