### ISSUE TITLE
Selecting Multiple Anime

### ISSUE THREAD

**Issue by shadow5013** [justfoolingaround/animdl#54]
Here is a snippet to help with parsing input.
``` Python3
def parse_range(a):
    List = []
    for element in a.split(','):
        parts = [int(x) for x in element.split('-')]
        if len(parts) == 1:
            List.append(parts[0])
        else:
            for i in range(min(parts), max(parts) + 1):
                List.append(i)
    # filtering doubles
    res = []
    [res.append(x) for x in List if x not in res]
    return res
```

**Comment by justfoolingaround** [comment]
I did already have the code standby lol, I just assumed selecting start and the end would be more than enough. 

```py
import re

def get_range_conditions(range_string):
    for matches in re.finditer(r"(?:([0-9]*):([0-9]*)|([0-9]+))", range_string):
        start, end, singular = matches.groups()
        if ((start or '').isdigit() and (end or '').isdigit()) and int(start) > int(end):
            start, end = end, start
        yield (lambda x, s=singular: int(singular) == x) if singular else (lambda x: True) if not (start or end) else (lambda x, s=start: x >= int(s)) if start and not end else (lambda x, e=end: x <= int(e)) if not start and end else (lambda x, s=start, e=end: int(s) <= x <= int(e))

def get_check(range_string):
    return lambda x: any(condition(x) for condition in get_range_conditions(range_string))
```
*also maybe because the code was utter hell.*

**Comment by ArjixWasTaken** [comment]
> Here is a snippet to help with parsing input.
> 
> ```python
> def parse_range(a):
>     List = []
>     for element in a.split(','):
>         parts = [int(x) for x in element.split('-')]
>         if len(parts) == 1:
>             List.append(parts[0])
>         else:
>             for i in range(min(parts), max(parts) + 1):
>                 List.append(i)
>     # filtering doubles
>     res = []
>     [res.append(x) for x in List if x not in res]
>     return res
> ```

Lmao, why not just 
```python
res = list(set(List))
```
why the extra step?

**Comment by ArjixWasTaken** [comment]
> I did already have the code standby lol, I just assumed selecting start and the end would be more than enough.
> 
> ```python
> import re
> 
> def get_range_conditions(range_string):
>     for matches in re.finditer(r"(?:([0-9]*):([0-9]*)|([0-9]+))", range_string):
>         start, end, singular = matches.groups()
>         if ((start or '').isdigit() and (end or '').isdigit()) and int(start) > int(end):
>             start, end = end, start
>         yield (lambda x, s=singular: int(singular) == x) if singular else (lambda x: True) if not (start or end) else (lambda x, s=start: x >= int(s)) if start and not end else (lambda x, e=end: x <= int(e)) if not start and end else (lambda x, s=start, e=end: int(s) <= x <= int(e))
> 
> def get_check(range_string):
>     return lambda x: any(condition(x) for condition in get_range_conditions(range_string))
> ```
> 
> _also maybe because the code was utter hell._

man used a generator in a use case that doesn't need it at all and it actually makes it more complicated...
That's the KR that I know 🤣

**Comment by shadow5013** [comment]
> > Here is a snippet to help with parsing input.
> > ```python
> > def parse_range(a):
> >     List = []
> >     for element in a.split(','):
> >         parts = [int(x) for x in element.split('-')]
> >         if len(parts) == 1:
> >             List.append(parts[0])
> >         else:
> >             for i in range(min(parts), max(parts) + 1):
> >                 List.append(i)
> >     # filtering doubles
> >     res = []
> >     [res.append(x) for x in List if x not in res]
> >     return res
> > ```
> 
> Lmao, why not just
> 
> ```python
> return list(set(List))
> ```
> 
> why the extra step?

Because set automatically sorts the list. You wouldn't want to download the sequel before the actual anime, would you?

**Comment by ArjixWasTaken** [comment]
> > > Here is a snippet to help with parsing input.
> > > ```python
> > > def parse_range(a):
> > >     List = []
> > >     for element in a.split(','):
> > >         parts = [int(x) for x in element.split('-')]
> > >         if len(parts) == 1:
> > >             List.append(parts[0])
> > >         else:
> > >             for i in range(min(parts), max(parts) + 1):
> > >                 List.append(i)
> > >     # filtering doubles
> > >     res = []
> > >     [res.append(x) for x in List if x not in res]
> > >     return res
> > > ```
> > 
> > Lmao, why not just
> > 
> > ```python
> > return list(set(List))
> > ```
> > 
> > why the extra step?
> 
> Because `set()` automatically sorts the list. You wouldn't want to download the sequel before the actual anime, would you?

Heh, I didn't think that thru

**Comment by justfoolingaround** [comment]
Aight so this has been added as a `-r` argument that replaces `-s` and `-e`. So I guess this can be closed now!
