### ISSUE TITLE
[Tenshi] Unable to grab links

### ISSUE THREAD

**Issue by z-9bqxxrp2pv** [justfoolingaround/animdl#60]
I've tried with other sites and it is working but in Tenshi, whatever link I use to it does not able to grab links. Probably needs to be fixed

**Comment by justfoolingaround** [comment]
I can't reproduce it. Can you give me the name of the anime and the episode?

![image](https://user-images.githubusercontent.com/79979949/132130183-12871e0d-118e-4124-9772-d8d611edd8b3.png)

**Comment by z-9bqxxrp2pv** [comment]
Sorry for the misinformation. The problem was on my end. I am using ubuntu and what I do is just extract the zip version then use `python animdl.py` to run which was the mistake. I should still need to run `python -m pip install .`  Thank you because I manage to fix it because of the image you've attached. Btw, kinda off topic but will 9anime still be fixed? 

I am unable to delete this issue to avoid further confusion but this can now be closed. Thanks again!

**Comment by justfoolingaround** [comment]
Ah well, glad you got to the solution.

Yeah, 9Anime will probably be re-added sometime in the future.
