### ISSUE TITLE
Option to specify download folder (not --title)

### ISSUE THREAD

**Issue by Epicguru** [justfoolingaround/animdl#61]
Hi, thanks for the great tool. It works great, but I did find the download folder quite un-intuitive.
There is the --title option, but this just specifies the folder name (which isn't particularly useful imho).

I had to inspect `downloader.py` to figure out where the episodes were actually being downloaded to. My first suggestion would be to clarify this, at least in the readme i.e. `Episodes are downloaded to your home folder (or user root on Windows)`.

Ideally I would love to see another option, perhaps replacing --title, that allows for the download folder to be specified, such as
`--folder "C:\Users\xxx\Downloads"` or maybe `--path "C:\Users\xxx\Downloads\Attack On Titan"`.

I can make these changes myself and submit a PR if that would be easier, but it should only be a small change.
Thanks.

**Comment by Epicguru** [comment]
I've just realized that it downloads relative to the working directory, which makes more sense.
But again, this isn't particularly obvious, so perhaps just editing the readme to let users know to run the command from within the desired download folder would be sufficient.

**Comment by justfoolingaround** [comment]
Thank you! I will mention that the downloads will take place in the relative directory in the readme.md.

Due to this functionality, I didn't resort to adding a path selector as cli path can be modified easily with `cd`.

**Comment by Epicguru** [comment]
Great, thanks. I'll close this now.
Again great tool, easily best available.
