### ISSUE TITLE
[Source Request] AnimeKaizoku

### ISSUE THREAD

**Issue by mnabid** [justfoolingaround/animdl#62]
https://animekaizoku.com

DDL site, has direct links and google drive.
Need to bypass `ouo.io` (I use [this userscript](https://greasyfork.org/en/scripts/419509-skipper-for-ouo-io-by-imba/code) on my browser).

**Comment by justfoolingaround** [comment]
Aight so this is not possible.

The userscript you're using is running on your browser. From what I can see, it only bypasses the "waiting" part of the site. There is a Google reCaptcha on that site (ouo.io), which cannot be bypassed, at least from what I can make public.

**Comment by mnabid** [comment]
>There is a Google reCaptcha on that site (ouo.io), which cannot be bypassed, at least from what I can make public.

Uhh...not sure I understood. I never got any recaptcha with this userscript.
So basically, this mechanism would work only for browsers, but not on CLI?

**GOOD NEWS...**
Found [this bypasser](https://github.com/milkysch/ouoio_bypass/blob/main/ouoio_bypass.py) on github, it works! (plus, it's written in python)

```bash
$ python ouoio_bypass.py "https://ouo.press/xbOlgc"

https://s.animekaizoku.com/2Mr5NOPnddq
```
