### ISSUE TITLE
IDM - Some episode is temporarily unavailable.

### ISSUE THREAD

**Issue by ajam123** [justfoolingaround/animdl#65]
Hi,

While downloading via IDM, some episodes have this error "This site is temporarily unavailable!". Is there any way to fix this problem without manually go to the site and download it?

**Comment by shadow5013** [comment]
Provider, anime, episode?

**Comment by ajam123** [comment]
Provider: Gogoanime
Anime: BanG Dream!
Episode: 09

**Comment by justfoolingaround** [comment]
Aight so, that error is associated with scraping and shows up when the episodes are not available in the sites.

By the time I'm checking this, the episodes are available on site and animdl is working fine with the anime you mentioned.

**Comment by ajam123** [comment]
The episodes are available yes, but unfortunately, I can't download it via --idm. It works without --idm though. It happened a lot to me, not sure why.

**Comment by justfoolingaround** [comment]
Seems to be an issue regarding extractions, possibly with the internet. There is no different extraction process for IDM. 

Let me know if this is still prevalent and I'll re-open this issue.
