### ISSUE TITLE
GogoAnime suddenly stopped working?

### ISSUE THREAD

**Issue by NavDevP** [justfoolingaround/animdl#67]
All streams are empty?
What happens here?

**Comment by justfoolingaround** [comment]
Yeah, apparently GogoAnime has their main server sorta messed up at the moment. I am planning on making use of their mirrors.

For now yeah, please resort to using other providers!

**Comment by NavDevP** [comment]
Actually, they remove the URLs from the download page. That's why we are not getting the `stream URLS`
I have a URL from which we can get stream URLs without **download page**.

URL FORMAT IS LIKE THIS -->
`https://goload.one/encrypt-ajax.php?id=d5TS5eMM9aJ9HYxe8tSURA==&title=Kingdom+3rd+Season+Episode+1&refer=https://gogoanime.pe/&ch=d41d8cd98f00b204e9800998ecf8427e&time=98867113131089352910`

this url provides m3u8 streams. Can you please try decoding this?

### _But it only work once then expire_

**Comment by NavDevP** [comment]
Brother can i have your mail id or something where I can send you suggestions related to gogo and animixplay

**Comment by justfoolingaround** [comment]
> Actually, they remove the URLs from the download page. That's why we are not getting the `stream URLS` I have a URL from which we can get stream URLs without **download page**.
> 
> URL FORMAT IS LIKE THIS --> `https://goload.one/encrypt-ajax.php?id=d5TS5eMM9aJ9HYxe8tSURA==&title=Kingdom+3rd+Season+Episode+1&refer=https://gogoanime.pe/&ch=d41d8cd98f00b204e9800998ecf8427e&time=98867113131089352910`
> 
> this url provides m3u8 streams. Can you please try decoding this?
> 
> ### _But it only work once then expire_

Yeah that still gives me 404. It is their server that's down. Don't worry, the link extraction from the download page will work.

I have also pushed a commit for using StreamSB for the time being.


> Brother can i have your mail id or something where I can send you suggestions related to gogo and animixplay. Im able to get link from Animix from animdl.

Yeah sure! You can contact me on Discord at KR#7700 or like you asked, the email is: kr.justfoolingaround@gmail.com.

**Comment by NavDevP** [comment]
I send you friend request from navyshot please accept

**Comment by justfoolingaround** [comment]
GogoAnime have now fixed their servers!

This should be working now!

**Comment by aflyingpumpkin** [comment]
I read that they allegedly fixed their servers but it seems they are still using the wack url scheme that gives 404 errors:
![image](https://user-images.githubusercontent.com/49350251/135870496-c314bb5f-1262-47bf-ab6a-c631842b8403.png)
https://goload.one/download?id=MTcxOTU0&typesub=Gogoanime-SUB&title=Love+Live%21+Superstar%21%21+Episode+10

**Comment by justfoolingaround** [comment]
I agree with the fact that the URLs are wack.

However, with a correct referal, it doesn't seem to give out 404 and is perfectly streamable.
