### ISSUE TITLE
Error In Working

### ISSUE THREAD

**Issue by Zeroo097** [justfoolingaround/animdl#69]
Whenever i run any command it shows traceback error

![image](https://user-images.githubusercontent.com/91909890/135899951-31da3ec9-9b0a-4d12-9896-f2d2d9cb3a43.png)
I am kinda new to these things please bare with me.Thank You

**Comment by justfoolingaround** [comment]
Oh, as it seems the unicode for colors aren't supported.

Don't worry,

```sh
py -X utf-8 -m animdl grab "haikyuu"
```
will work.

**Comment by Zeroo097** [comment]
Is it one time process or I have to do it everytime.And is there a way to install that unicode colour thing
BTW Thank You For Your Help

**Comment by justfoolingaround** [comment]
Yeah, you need to do it every time. 

The only way to fix this would be to switch terminals to `cmd`, Windows Terminal or something else.

**Comment by Zeroo097** [comment]
Ok so i used cmd everything is working fine But But When i download from animepahe it doesnt use idm even after mentioning it in the command and also how do i select if i only want to download episode 2.i used -r two but it doesnt seem to work full command that is used is written below.

animdl download haikyuu --idm -r two

**Comment by justfoolingaround** [comment]
Yeah IDM doesn't support HLS downloading (content from AnimePahe is HLS). This is handled by an internal downloader.

**Comment by Zeroo097** [comment]
Ok then the issue is fixed thank you for your time.
