### ISSUE TITLE
Please add Openssl

### ISSUE THREAD

**Issue by Karambe69** [justfoolingaround/animdl#71]
So i used your script it works fine but the download speed is not thay great.And i can't use idm in animepahe.Is there a way i can use ssl to download anime from AnimePahe as it will drastically increase download speed.

**Comment by justfoolingaround** [comment]
Okay okay, so um, can you explain what do you mean by "adding SSL" and it is bound to increase internet speeds?

**Comment by justfoolingaround** [comment]
See #70.
