### ISSUE TITLE
Show Version (-v)

### ISSUE THREAD

**Issue by Anu-bhav** [justfoolingaround/animdl#79]
Kindly add a `-v `flag to display the current version or add the current version on the banner screen.

It is not easy to know the current version of animdl unless `pip show animdl` is ran

![image](https://user-images.githubusercontent.com/41940586/143259260-1ed4136b-7af2-4022-b10d-a623fca2ee92.png)

**Comment by justfoolingaround** [comment]
<p align="center">Good suggestion! Added <code><img src="https://canary.discord.com/assets/212e30e47232be03033a87dc58edaa95.svg" height=15px></code></p>
