### ISSUE TITLE
error when i try to install the software on windows 10

### ISSUE THREAD

**Issue by Avrozavr** [justfoolingaround/animdl#8]
C:\Users\Avr>pip install git+https://github.com/justfoolingaround/animdl-install
Collecting git+https://github.com/justfoolingaround/animdl-install
  Cloning https://github.com/justfoolingaround/animdl-install to c:\users\public\documents\wondershare\creatortemp\pip-req-build-5sa9_v3g
  Running command git clone -q https://github.com/justfoolingaround/animdl-install 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-5sa9_v3g'
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\avr\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-req-build-5sa9_v3g\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-req-build-5sa9_v3g\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-pip-egg-info-93f6fxo6'
         cwd: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-5sa9_v3g\
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-5sa9_v3g\setup.py", line 2, in <module>
        from animdl.__version__ import __core__
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-5sa9_v3g\animdl\__init__.py", line 1, in <module>
        from . import core
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-5sa9_v3g\animdl\core\__init__.py", line 2, in <module>
        from .downloader.download import internal_download
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-5sa9_v3g\animdl\core\downloader\__init__.py", line 1, in <module>
        from .download import \
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-build-5sa9_v3g\animdl\core\downloader\download.py", line 6, in <module>
        from tqdm import tqdm
    ModuleNotFoundError: No module named 'tqdm'
    ----------------------------------------
WARNING: Discarding git+https://github.com/justfoolingaround/animdl-install. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I am new to github, so sorry if i will make mistakes.

**Comment by justfoolingaround** [comment]
Aight, so, give `pip install git+https://github.com/justfoolingaround/animdl-install` a re-run. 

Issue was caused due to the `.__init__` attribute importing the codebase that caused the code to auto-run during installation without installing what it requires forehand.

Thanks for reporting this issue as this bug in the installer wouldn't be identified if it weren't for this!
