### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by gabrilend** [justfoolingaround/animdl#82]
Hi, I downloaded the project using the command specified in the readme:

python -m pip install git+https://www.github.com/justfoolingaround/animdl

and it seemed to download correctly. No error messages, just pip's downloading messages. But when I type "animdl" into the terminal, it says "command not found" - is there a directory I need to put on my path? Or alternatively, where is the program installed? I have MPV and git installed already.

**Comment by justfoolingaround** [comment]
(Sorry for the late response!)

As it seems Python's scripts folder is not in your PATH. You can still access the project using

```
python -m animdl
```

On Windows, the scripts folder is located at:

```
%USERPROFILE%\AppData\Local\Programs\Python\Python39\Scripts\
```

or, 

```
%LOCALAPPDATA%\Programs\Python\Python39\Scripts\
````

This is where all your scripts go. The project installs itself onto Python!

**Comment by justfoolingaround** [comment]
Hopefully this has solved your issue! If it hasn't we'll just reopen this in the future!
