### ISSUE TITLE
gogoanime broken

### ISSUE THREAD

**Issue by thegamerx1** [justfoolingaround/animdl#84]
![02_12_2021_cmd_0x7YQW4cLi](https://user-images.githubusercontent.com/34986564/144504256-e0b511e6-3010-4f69-a3c1-13498c4d86c4.png)
Episode choosing in gogoanime is broken even after updating

**Comment by justfoolingaround** [comment]
Seems to be working fine. This may be because of the commit differences. GogoAnime underwent various changes previously.

![](https://user-images.githubusercontent.com/79979949/144614187-44bcbe86-26df-4f4e-a316-4a629b81a644.png)

Something as simple as 

```
pip uninstall animdl && pip install git+https://github.com/justfoolingaround/animdl
````

will fix this!
