### ISSUE TITLE
Installation failling in macOS 10.13.6

### ISSUE THREAD

**Issue by fgyamauti** [justfoolingaround/animdl#88]
Probably something stupid. Maybe I'm screwing up something. Still, after `python -m pip install https://www.github.com/justfoolingaround/animdl` I've got the following 

  `Defaulting to user installation because normal site-packages is not writeable`
  `Collecting https://www.github.com/justfoolingaround/animdl`
  `Downloading https://www.github.com/justfoolingaround/animdl`
    ` \ 222 kB 6.2 MB/s`
   `ERROR: Cannot unpack file /private/var/folders/kk/mgs219710f56dsmzw30mh89m0000gn/T/pip-unpack-rurmks0i/animdl (downloaded from /private/var/folders/kk/mgs219710f56dsmzw30mh89m0000gn/T/pip-req-build-goc7rk5c, content-type: text/html; charset=utf-8); cannot detect archive format`
`ERROR: Cannot determine archive format of /private/var/folders/kk/mgs219710f56dsmzw30mh89m0000gn/T/pip-req-build-goc7rk5c
`
  By the way, I'm using Python 3.10 and the latest version of pip. My OS is macOS 10.13.6. Python 3.10 was installed using MacPorts, so everything is further inside /opt/local . 

   Thanks in advance.

**Comment by justfoolingaround** [comment]
You missed a "git+"!

What you did was:
```
python -m pip install https://www.github.com/justfoolingaround/animdl
```
What needed to be done was:
```
python -m pip install git+https://www.github.com/justfoolingaround/animdl
```

Let me know if this still persists. You can also try `python3` instead of `python`.

**Comment by fgyamauti** [comment]
Oh!My bad. Indeed, I was unaware of the syntax. Working perfectly. I'm closing the issue. It's a shame animdl has a lot less recognition than ani-cli. Animdl is a lot faster and there are more scrappers.
