### ISSUE TITLE
how to add and use mpv

### ISSUE THREAD

**Issue by Avrozavr** [justfoolingaround/animdl#9]
Sorry to bother you again, the installation went good, now I can't figure out how to add and use mpv, and how to select video quality.

**Comment by justfoolingaround** [comment]
From the previous issue, I assume you're on Windows.

For Windows, just go [here.](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20210613-git-03b9f8e.7z/download) That link goes to the latest git release for mpv's Windows binary and should immediately start downloading.

Now, just extract the contents of that archive to a directory.

If you know how to add that directory to your PATH, add it and now `animdl` will immediately show the previously hidden `stream` command. You basically use mpv from that command.

If you don't know how to add that directory to your PATH, just open the terminal/console on that directory (cd to that directory) and `animdl`'s `stream` command will work for that directory.

It is highly recommended to add that directory (with mpv) to your PATH; to do that, just follow the [instructions here](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/).

**Comment by Avrozavr** [comment]
Thank you, I understood what I need to do. You are awesome!
